### ISSUE TITLE
Fehler: Adapter startet nicht Version 0.9.1 nach wie vor nicht gelöst!

### ISSUE THREAD

**Issue by hilde0407** [jensweigele/ioBroker.yahka#110]
Bei mir ist das Problem, wie hier beschrieben: [https://github.com/jensweigele/ioBroker.yahka/issues/105](url) nach wie vor nicht gelöst! Ich habe den Adapter komplett deinstalliert und über GitHub neu installiert, leider der selbe Fehler:

host.volker-BT3-Pro | 2019-03-09 21:13:53.131 | info | Restart adapter system.adapter.yahka.0 because enabled
-- | -- | -- | --
host.volker-BT3-Pro | 2019-03-09 21:13:53.131 | error | instance system.adapter.yahka.0 terminated with code 1 ()
host.volker-BT3-Pro | 2019-03-09 21:13:53.131 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.yahka/main.js:84:18
host.volker-BT3-Pro | 2019-03-09 21:13:53.131 | error | Caught by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
host.volker-BT3-Pro | 2019-03-09 21:13:53.130 | error | Caught by controller[0]: at Object../main.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:290:30)
host.volker-BT3-Pro | 2019-03-09 21:13:53.130 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.yahka/main.js:271:17)
host.volker-BT3-Pro | 2019-03-09 21:13:53.130 | error | Caught by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
host.volker-BT3-Pro | 2019-03-09 21:13:53.130 | error | Caught by controller[0]: at Object../yahka.ioBroker-adapter.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:2326:16)
host.volker-BT3-Pro | 2019-03-09 21:13:53.130 | error | Caught by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
host.volker-BT3-Pro | 2019-03-09 21:13:53.130 | error | Caught by controller[0]: at Object../yahka.homekit-bridge.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:1764:25)
host.volker-BT3-Pro | 2019-03-09 21:13:53.130 | error | Caught by controller[0]: at Object.importHAPCommunityTypesAndFixes (/opt/iobroker/node_modules/iobroker.yahka/main.js:382:26)
host.volker-BT3-Pro | 2019-03-09 21:13:53.129 | error | Caught by controller[0]: at module.exports (/opt/iobroker/node_modules/hap-nodejs-community-types/types.js:920:45)
host.volker-BT3-Pro | 2019-03-09 21:13:53.129 | error | Caught by controller[0]: TypeError: Cannot read property 'generate' of undefined
host.volker-BT3-Pro | 2019-03-09 21:13:53.129 | error | Caught by controller[0]: ^
host.volker-BT3-Pro | 2019-03-09 21:13:53.129 | error | Caught by controller[0]: CommunityTypes.InputVoltageAC.UUID = UUID.generate('CommunityTypes:usagedevice:InputVoltageAC');
host.volker-BT3-Pro | 2019-03-09 21:13:53.128 | error | Caught by controller[0]: /opt/iobroker/node_modules/hap-nodejs-community-types/types.js:920
host.volker-BT3-Pro | 2019-03-09 21:13:52.491 | info | instance system.adapter.yahka.0 started with pid 28009

``

**Comment by darkbrain85** [comment]
Kann ich bestätigen! Selbe Fehlermeldungen wie oben bereits genannt!

**Comment by rbrose** [comment]
Naja der fix wurde gestern erst aufgenommen in den master Branch. Ein neues Release wurde nicht erstellt. Installierst du von den sourcen oder Release?

**Comment by darkbrain85** [comment]
Wenn ich in iobroker manuell mit dem Link

https://github.com/jensweigele/ioBroker.yahka

installiere, nimmt er doch die source, oder?

**Comment by Inflight69** [comment]
Das selbe mit meiner Installation.
Node.js: v10.15.3
NPM: 6.9.0


2019-03-10 22:28:04.614 - info: host.raspberrypi Restart adapter system.adapter.yahka.0 because enabled
--
2019-03-10 22:28:34.633 - info: host.raspberrypi instance system.adapter.yahka.0 started with pid 12328
2019-03-10 22:28:35.570 - error: Caught by controller[0]: /opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs-community-types/types.js:920
2019-03-10 22:28:35.570 - error: Caught by controller[0]: CommunityTypes.InputVoltageAC.UUID = UUID.generate('CommunityTypes:usagedevice:InputVoltageAC');
2019-03-10 22:28:35.570 - error: Caught by controller[0]: ^
2019-03-10 22:28:35.571 - error: Caught by controller[0]: TypeError: Cannot read property 'generate' of undefined
2019-03-10 22:28:35.571 - error: Caught by controller[0]: at module.exports (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs-community-types/types.js:920:45)
2019-03-10 22:28:35.571 - error: Caught by controller[0]: at Object.importHAPCommunityTypesAndFixes (/opt/iobroker/node_modules/iobroker.yahka/main.js:382:26)
2019-03-10 22:28:35.571 - error: Caught by controller[0]: at Object../yahka.homekit-bridge.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:1764:25)
2019-03-10 22:28:35.571 - error: Caught by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
2019-03-10 22:28:35.571 - error: Caught by controller[0]: at Object../yahka.ioBroker-adapter.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:2326:16)
2019-03-10 22:28:35.571 - error: Caught by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
2019-03-10 22:28:35.572 - error: Caught by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.yahka/main.js:271:17)
2019-03-10 22:28:35.572 - error: Caught by controller[0]: at Object../main.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:290:30)
2019-03-10 22:28:35.572 - error: Caught by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
2019-03-10 22:28:35.572 - error: Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.yahka/main.js:84:18
2019-03-10 22:28:35.572 - error: host.raspberrypi instance system.adapter.yahka.0 terminated with code 1 ()
2019-03-10 22:28:35.572 - info: host.raspberrypi Restart adapter system.adapter.yahka.0 because enabled

Und so wiederholt sich dann das immer wieder...

**Comment by jensweigele** [comment]
Weitere Diskussion in #105
