### ISSUE TITLE
Adapter crashes when adding yahka in homekit

### ISSUE THREAD

**Issue by Black-Lemon** [jensweigele/ioBroker.yahka#121]
when I enter the pincode for adding the adapter in homekit, it crashes for me. Here's my logfile from restarting the adapter > entering pin > crash:

2019-04-26 13:47:48.535 - info: host.raspberrypi object change system.adapter.yahka.0
--
2019-04-26 13:47:48.549 - info: yahka.0 cleaning up ...
2019-04-26 13:47:48.542 - info: host.raspberrypi stopInstance system.adapter.yahka.0
2019-04-26 13:47:48.543 - info: host.raspberrypi stopInstance system.adapter.yahka.0 killing pid 31973
2019-04-26 13:47:48.553 - info: yahka.0 cleaned up ...
2019-04-26 13:47:48.575 - info: yahka.0 terminating
2019-04-26 13:47:48.628 - info: host.raspberrypi instance system.adapter.yahka.0 terminated with code 0 (OK)
2019-04-26 13:47:51.088 - info: host.raspberrypi instance system.adapter.yahka.0 started with pid 994
2019-04-26 13:47:55.129 - info: yahka.0 starting. Version 0.9.2 in /opt/iobroker/node_modules/iobroker.yahka, node: v6.16.0
2019-04-26 13:47:55.241 - info: yahka.0 adapter ready, checking config
2019-04-26 13:48:16.909 - error: yahka.0 uncaught exception: "list" argument must be an Array of Buffers
2019-04-26 13:48:16.913 - error: yahka.0 TypeError: "list" argument must be an Array of Buffers
at Function.Buffer.concat (buffer.js:314:13)
at Object.encode (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
at Object.encode (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
at Object.encode (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
at HAPServer._handlePairStepFive (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:459:21)
at HAPServer._handlePairStepFour (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:439:8)
at HAPServer._handlePairStepThree (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:413:8)
at HAPServer._handlePair (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:315:10)
at HAPServer. (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
at emitNone (events.js:86:13)
2019-04-26 13:48:16.916 - info: yahka.0 cleaning up ...
2019-04-26 13:48:16.918 - info: yahka.0 cleaned up ...
2019-04-26 13:48:17.039 - error: Caught by controller[0]: TypeError: "list" argument must be an Array of Buffers
2019-04-26 13:48:17.041 - error: Caught by controller[0]: at Function.Buffer.concat (buffer.js:314:13)
2019-04-26 13:48:17.042 - error: Caught by controller[0]: at Object.encode (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
2019-04-26 13:48:17.042 - error: Caught by controller[0]: at Object.encode (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
2019-04-26 13:48:17.043 - error: Caught by controller[0]: at Object.encode (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
2019-04-26 13:48:17.043 - error: Caught by controller[0]: at HAPServer._handlePairStepFive (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:459:21)
2019-04-26 13:48:17.043 - error: Caught by controller[0]: at HAPServer._handlePairStepFour (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:439:8)
2019-04-26 13:48:17.044 - error: Caught by controller[0]: at HAPServer._handlePairStepThree (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:413:8)
2019-04-26 13:48:17.044 - error: Caught by controller[0]: at HAPServer._handlePair (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:315:10)
2019-04-26 13:48:17.044 - error: Caught by controller[0]: at HAPServer. (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
2019-04-26 13:48:17.045 - error: Caught by controller[0]: at emitNone (events.js:86:13)
2019-04-26 13:48:17.045 - error: host.raspberrypi instance system.adapter.yahka.0 terminated with code 0 (OK)
2019-04-26 13:48:17.046 - info: host.raspberrypi Restart adapter system.adapter.yahka.0 because enabled

**Comment by Markus78224** [comment]
I face the same problem

I already updated my Raspbian, but without any change. Node.js is on 6.14.1. May be it's too old? 
 

2019-05-01 11:35:46.552 - info: host.raspberrypi instance system.adapter.yahka.0 started with pid 6156
2019-05-01 11:35:48.830 - info: yahka.0 starting. Version 0.9.2 in /opt/iobroker/node_modules/iobroker.yahka, node: v6.14.1
2019-05-01 11:35:48.896 - info: yahka.0 adapter ready, checking config
2019-05-01 11:35:48.922 - info: yahka.0 adding Licht with UUID: f5a9c7c8-3bf9-48b3-8441-909729e85566
2019-05-01 11:37:30.024 - error: yahka.0 uncaught exception: "list" argument must be an Array of Buffers
2019-05-01 11:37:30.026 - error: yahka.0 TypeError: "list" argument must be an Array of Buffers
at Function.Buffer.concat (buffer.js:314:13)
at Object.encode (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
at Object.encode (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
at Object.encode (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
at HAPServer._handlePairStepFive (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:459:21)
at HAPServer._handlePairStepFour (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:439:8)
at HAPServer._handlePairStepThree (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:413:8)
at HAPServer._handlePair (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:315:10)
at HAPServer. (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
at emitNone (events.js:86:13)
2019-05-01 11:37:30.028 - info: yahka.0 cleaning up ...

**Comment by Dalmapalma** [comment]
exactly same issue here - after I upgraded my adapter

Is there any solution available?

**Comment by Dalmapalma** [comment]
any updates?

**Comment by Markus78224** [comment]
I solved the problem by updating node.js to 8.16.0

**Comment by Black-Lemon** [comment]
i got 6.17.1
can i upgrad to a new mainversion without breaking anything?

normaly i do…
>  sudo apt-get update
>  sudo apt-get upgrade
>  sudo apt-get dist-upgrade
>  sudo apt-get autoremove
…thought, this updates everything to the newest

(sorry. me = complete linux-noob)

**Comment by Markus78224** [comment]
I'm a Linux-noob too, but as far as I understood, node.js and NPM are not updated by the standard update/upgrade process.

I followed this (German) instruction: [http://www.iobroker.net/docu/?page_id=8323&lang=de#Upgrade_von_nodejs_und_npm](url)

! Make a Backup !

`sudo iobroker stop`
`sudo apt-get --purge remove node nodejs`

(I got the message that Node package is not installed, but this seems to be OK as it is only linked)

`sudo apt-get autoremove`
`sudo reboot `

after the reboot: 

`sudo curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -`
`sudo apt-get install -y build-essential libavahi-compat-libdnssd-dev libudev-dev libpam0g-dev nodejs`
`sudo reboot`

After the second reboot you have to rebuild the installed adapter for the new node.js version
Change to the IObroker subfolder (normally with `CD /opt/iobroker`  )

`sudo npm rebuild`
(Here I got some warnings, but it worked. Takes several minutes on a Raspi)

`sudo start iobroker`
(it already ran, as it auto-starts in my installation) 

After this It was possible to add yahka in homekit within seconds

Hope this helps

**Comment by Dalmapalma** [comment]
Big thank you...I could solve it with your instruction :-)

**Comment by Black-Lemon** [comment]
i ran into some problems. Said, NPM was newer than supported (luckily gave me the needed command to do it).
then "sudo npm rebuild" wouldn't run through, but worked after doing it 3 times in a row.
Then half of my adapters were working again (other half not).
After running update some started working again (like js-Adapter).
Had to completely uninstall Tradfri/TK/Zigbee-Adapter and reinstall them.
But now everything seams to be running smoothly.

Thank you!

**Comment by algermi** [comment]
hey guys, i must rebuild npm almost twice a day. is there an opportunity to downgrade to 0.7.1.
the yahoo adapter crash's after reboot IoBroker
