### ISSUE TITLE
Adapter startet nicht mehr: ELRD

### ISSUE THREAD

**Issue by algermi** [jensweigele/ioBroker.yahka#127]
Servus zusammen, mein Adapter startet seit dem Upgrade auf 0.9.2 nicht mehr. Vorher hatte ich 0.7.1 im Einsatz. Auszug aus dem LOG:

Jemand eine Idee?

2019-06-18 13:18:20.435 - info: host.ioBroker Restart adapter system.adapter.yahka.0 because enabled
--
2019-06-18 13:18:50.520 - info: host.ioBroker instance system.adapter.yahka.0 started with pid 3563
2019-06-18 13:18:52.700 - info: yahka.0 States connected to redis: 127.0.0.1:6379
2019-06-18 13:18:52.799 - info: yahka.0 starting. Version 0.9.2 in /opt/iobroker/node_modules/iobroker.yahka, node: v6.10.0
2019-06-18 13:18:52.911 - info: yahka.0 adapter ready, checking config
2019-06-18 13:18:52.936 - info: yahka.0 adding Lichtleiste TV with UUID: a7ceaf92-1823-4a0f-b59a-de5a453461d9
2019-06-18 13:18:52.967 - info: yahka.0 adding Haustür with UUID: 13855017-43a0-4270-ae26-314be9de08d7
2019-06-18 13:18:52.976 - info: yahka.0 adding Kinderzimmerfenster with UUID: 4ebbd287-d327-4a58-972f-59a61eb11627
2019-06-18 13:18:52.980 - info: yahka.0 adding Kellertüre with UUID: 5c10949a-7ca2-4cb5-a1eb-671b9a03f96c
2019-06-18 13:18:52.983 - info: yahka.0 adding Eingangsbeleuchtung with UUID: 94f2edac-6f29-4463-a08f-dc584f339bd6
2019-06-18 13:18:52.988 - info: yahka.0 adding Badezimmerfenster with UUID: e11a5741-533d-4df2-ba50-59597444abf7
2019-06-18 13:18:52.991 - info: yahka.0 adding Rauchmelder Keller with UUID: 645c95e8-2ca4-4483-aa73-61fd6b63eef6
2019-06-18 13:18:53.004 - info: yahka.0 adding Rauchmelder Flur with UUID: cf707800-75b8-4391-9495-1b3c1585459f
2019-06-18 13:18:53.010 - info: yahka.0 adding Dachfenster Kinderzimmer with UUID: 9cbfc61b-cb03-4ad8-a826-c2362c7cf330
2019-06-18 13:18:53.013 - info: yahka.0 adding Licht Garage with UUID: 325f7802-2439-481d-a451-b4dfed8de6e3
2019-06-18 13:18:53.017 - info: yahka.0 adding Außenbeleuchtung Hofseite with UUID: 50af6921-bfd2-45e7-80b0-597fdcd05d1a
2019-06-18 13:18:53.020 - info: yahka.0 adding Pool Pumpe with UUID: af0065ee-439d-4dd0-8aa5-5c19699d7277
2019-06-18 13:18:53.023 - info: yahka.0 adding Bewässerung Vorgarten with UUID: 0c45e4f8-38fe-443f-ab4d-c6e44f621fd7
2019-06-18 13:18:53.026 - info: yahka.0 adding Bewässerung Tropfschlauch with UUID: b2c900da-c136-4bda-a0fa-4170e002b678
2019-06-18 13:18:53.030 - info: yahka.0 adding Bewässerung Rasen Terrasse with UUID: 6245ef18-986f-4242-b189-87c668977e9d
2019-06-18 13:18:53.033 - info: yahka.0 adding Bewässerung Rasen Hinten with UUID: 129136be-8d88-4586-adcb-151b8fa4c4dd
2019-06-18 13:18:53.049 - info: yahka.0 adding Außenbeleuchtung Vorgarten with UUID: 899b5653-acde-4e9d-9017-a5eb37fcaea0
2019-06-18 13:18:53.053 - info: yahka.0 adding Terrassentüre with UUID: 61ba0ee6-2613-4654-b21b-dad49d709cae
2019-06-18 13:18:53.059 - info: yahka.0 adding Alex@Home with UUID: d1d9375a-8c08-4e7e-bf01-20dd5fc2b074
2019-06-18 13:18:53.070 - info: yahka.0 adding Saskia@Home with UUID: e5128137-81da-43e5-918a-2cc0545d261a
2019-06-18 13:18:53.074 - info: yahka.0 adding Gartenspot with UUID: 77715a11-68bc-4f81-a443-489348a6dea5
2019-06-18 13:18:53.083 - info: yahka.0 adding LED Grilleck with UUID: 27ec5482-fabd-4c35-9544-6647cafc7bf4
2019-06-18 13:18:53.096 - info: yahka.0 adding LED Beleuchtung Garagentore with UUID: 888bdd81-9147-4bec-820e-0558606ea4ae
2019-06-18 13:18:53.102 - info: yahka.0 adding Heizung Vorlauf with UUID: 68adb72d-4ebb-4409-a945-75eeaf7556e9
2019-06-18 13:18:53.108 - info: yahka.0 adding Heizung Rücklauf with UUID: ece3fed0-73b1-4604-b21f-5ce6d70b4f44
2019-06-18 13:18:53.112 - info: yahka.0 adding LED Beleuchtung Terrasse with UUID: 7af45625-61ce-4ec3-8db0-aa3e926600ad
2019-06-18 13:18:53.134 - info: yahka.0 adding LED Pooleck with UUID: a91f6f61-dc3c-4df6-a40d-f76a4b1fc89d
2019-06-18 13:18:53.142 - info: yahka.0 adding LED Baumbeleuchtung with UUID: 18cfb2ba-0780-4d3f-8296-399918d52f99
2019-06-18 13:18:53.145 - info: yahka.0 adding Heizkreislauf Küche with UUID: 6e0c90d6-4f6f-4467-8361-77dba7f200e5
2019-06-18 13:18:53.147 - info: yahka.0 adding Heizkreislauf Flur WC with UUID: ca818a86-c7c7-4472-8181-c1ea2acc703e
2019-06-18 13:18:53.152 - info: yahka.0 adding Heizkreislauf Esszimmer with UUID: a7e1c4d8-7c1a-4083-bc53-e4dbc2a901a5
2019-06-18 13:18:53.154 - info: yahka.0 adding Heizkreislauf Wohnzimmer with UUID: 433ff736-caaf-4fce-a1aa-a2c3a8a6ffdc
2019-06-18 13:18:53.157 - info: yahka.0 adding Heizkreislauf Badezimmer with UUID: 80a2c211-55e9-42ad-8e59-41d439982b24
2019-06-18 13:18:53.160 - info: yahka.0 adding ro wz links with UUID: 65b75f18-488a-47b6-8c20-77a84a671691
2019-06-18 13:18:53.176 - info: yahka.0 adding ro wz Mitte with UUID: d88f061e-05ab-403a-ac20-5adf53618ea3
2019-06-18 13:18:53.190 - info: yahka.0 adding ro wz rechts with UUID: 047f892d-4be4-44c9-b443-17453b65b5bf
2019-06-18 13:18:53.198 - info: yahka.0 adding ro galerie with UUID: 04676ff1-2aed-44c0-bb1f-5d5be75a1eef
2019-06-18 13:18:53.206 - info: yahka.0 adding Schrankbeleuchtung Küche with UUID: 7daf390e-5f70-4e65-b947-149caf303c28
2019-06-18 13:18:53.209 - info: yahka.0 adding Thermostat Kinderzimmer with UUID: 5b0ef458-e9d7-4916-ab27-db2bbc6eadce
2019-06-18 13:18:53.224 - info: yahka.0 adding Thermostat Handtuchheizkörper with UUID: e9ba4667-a6c9-4849-8cd0-c9ad564ca98d
2019-06-18 13:18:53.231 - info: yahka.0 adding Küchenbeleuchtung Fenster with UUID: b35f34df-21bb-4770-8fad-d0d60d59dea2
2019-06-18 13:18:53.234 - info: yahka.0 adding Terrassenstufe with UUID: 93b338b3-6d47-4f43-8537-278e0e1fe4e2
2019-06-18 13:18:54.813 - error: yahka.0 uncaught exception: "list" argument must be an Array of Buffers
2019-06-18 13:18:54.814 - error: yahka.0 TypeError: "list" argument must be an Array of Buffers
at Function.Buffer.concat (buffer.js:314:13)
at Object.encode (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
at Object.encode (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
at HAPServer._handlePairVerifyStepOne (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
at HAPServer._handlePairVerify (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
at HAPServer. (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
at emitNone (events.js:86:13)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
2019-06-18 13:18:54.816 - info: yahka.0 cleaning up ...
2019-06-18 13:18:54.817 - info: yahka.0 cleaned up ...
2019-06-18 13:18:54.855 - info: yahka.0 terminating
2019-06-18 13:18:58.014 - error: Caught by controller[0]: HAP Warning: Characteristic 00000025-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000087-0000-1000-8000-0026BB765291. Adding anyway.
2019-06-18 13:18:58.015 - error: Caught by controller[0]: HAP Warning: Characteristic 00000025-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000087-0000-1000-8000-0026BB765291. Adding anyway.
2019-06-18 13:18:58.016 - error: Caught by controller[1]: TypeError: "list" argument must be an Array of Buffers
2019-06-18 13:18:58.016 - error: Caught by controller[1]: at Function.Buffer.concat (buffer.js:314:13)
2019-06-18 13:18:58.016 - error: Caught by controller[1]: at Object.encode (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
2019-06-18 13:18:58.016 - error: Caught by controller[1]: at Object.encode (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
2019-06-18 13:18:58.017 - error: Caught by controller[1]: at HAPServer._handlePairVerifyStepOne (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
2019-06-18 13:18:58.017 - error: Caught by controller[1]: at HAPServer._handlePairVerify (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
2019-06-18 13:18:58.017 - error: Caught by controller[1]: at HAPServer. (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
2019-06-18 13:18:58.017 - error: Caught by controller[1]: at emitNone (events.js:86:13)
2019-06-18 13:18:58.017 - error: Caught by controller[1]: at IncomingMessage.emit (events.js:185:7)
2019-06-18 13:18:58.017 - error: Caught by controller[1]: at endReadableNT (_stream_readable.js:974:12)
2019-06-18 13:18:58.018 - error: Caught by controller[1]: at _combinedTickCallback (internal/process/next_tick.js:74:11)
2019-06-18 13:18:58.018 - error: host.ioBroker instance system.adapter.yahka.0 terminated with code 0 (OK)

**Comment by nicoh88** [comment]
@algermi 

Du konntest dein Problem sicher mit der aktuellen Version `0.11.0` über das ioBroker Repo lösen oder?

**Comment by nicoh88** [comment]
_Leider, keine Antwort. Schließe Issue!  
Unfortunately, no answer. Close Issue!_
