### ISSUE TITLE
latest Beta adpater crashing 

### ISSUE THREAD

**Issue by noaboa97** [jensweigele/ioBroker.yahka#129]
Hi, 

So I updated to the latest Beta, to my disapointment the adapter crahsed immediatly upon starting.
I tried installed the latest release but ioBroker won't replace the files and just make a second adapter.
How can I switch back to the latest release?
I already tried to download the npm on the cli but that didn't work.
Is there somewhere a config file which I could save and add to the new adapter?

I also had a glimpse at the new services but couldn't find any way to turn on and in general I didn't understand a lot of the names in the services and what it would do.

Error in Log:

`
```

2019-06-24 22:14:46.742  - error:  Caught by controller[0]: HAP Warning: Characteristic  00000008-0000-1000-8000-0026BB765291 not in required or optional  characteristics for service 00000049-0000-1000-8000-0026BB765291. Adding  anyway.
--
2019-06-24 22:14:46.744  - error: Caught by controller[1]: TypeError: "list" argument must be an Array of Buffers
2019-06-24 22:14:46.745  - error: Caught by controller[1]:     at Function.Buffer.concat (buffer.js:314:13)
2019-06-24 22:14:46.746  - error:  Caught by controller[1]:     at Object.encode  (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
2019-06-24 22:14:46.747  - error:  Caught by controller[1]:     at Object.encode  (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
2019-06-24 22:14:46.748  - error:  Caught by controller[1]:     at HAPServer._handlePairVerifyStepOne  (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
2019-06-24 22:14:46.749  - error:  Caught by controller[1]:     at HAPServer._handlePairVerify  (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
2019-06-24 22:14:46.750  - error: Caught by controller[1]:     at HAPServer. (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
2019-06-24 22:14:46.751  - error: Caught by controller[1]:     at emitNone (events.js:86:13)
2019-06-24 22:14:46.752  - error: Caught by controller[1]:     at IncomingMessage.emit (events.js:185:7)
2019-06-24 22:14:46.753  - error: Caught by controller[1]:     at endReadableNT (_stream_readable.js:974:12)
2019-06-24 22:14:46.754  - error: Caught by controller[1]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2019-06-24 22:14:46.755  - error: Caught by controller[1]: TypeError: "list" argument must be an Array of Buffers
2019-06-24 22:14:46.756  - error: Caught by controller[1]:     at Function.Buffer.concat (buffer.js:314:13)
2019-06-24 22:14:46.757  - error:  Caught by controller[1]:     at Object.encode  (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
2019-06-24 22:14:46.758  - error:  Caught by controller[1]:     at Object.encode  (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
2019-06-24 22:14:46.759  - error:  Caught by controller[1]:     at HAPServer._handlePairVerifyStepOne  (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
2019-06-24 22:14:46.762  - error:  Caught by controller[1]:     at HAPServer._handlePairVerify  (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
2019-06-24 22:14:46.763  - error: Caught by controller[1]:     at HAPServer. (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
2019-06-24 22:14:46.765  - error: Caught by controller[1]:     at emitNone (events.js:86:13)
2019-06-24 22:14:46.766  - error: Caught by controller[1]:     at IncomingMessage.emit (events.js:185:7)
2019-06-24 22:14:46.766  - error: Caught by controller[1]:     at endReadableNT (_stream_readable.js:974:12)
2019-06-24 22:14:46.767  - error: Caught by controller[1]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2019-06-24 22:14:46.769  - error: Caught by controller[1]: TypeError: "list" argument must be an Array of Buffers
2019-06-24 22:14:46.770  - error: Caught by controller[1]:     at Function.Buffer.concat (buffer.js:314:13)
2019-06-24 22:14:46.770  - error:  Caught by controller[1]:     at Object.encode  (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
2019-06-24 22:14:46.771  - error:  Caught by controller[1]:     at Object.encode  (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
2019-06-24 22:14:46.772  - error:  Caught by controller[1]:     at HAPServer._handlePairVerifyStepOne  (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
2019-06-24 22:14:46.773  - error:  Caught by controller[1]:     at HAPServer._handlePairVerify  (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
2019-06-24 22:14:46.774  - error: Caught by controller[1]:     at HAPServer. (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
2019-06-24 22:14:46.774  - error: Caught by controller[1]:     at emitNone (events.js:86:13)
2019-06-24 22:14:46.775  - error: Caught by controller[1]:     at IncomingMessage.emit (events.js:185:7)
2019-06-24 22:14:46.776  - error: Caught by controller[1]:     at endReadableNT (_stream_readable.js:974:12)
2019-06-24 22:14:46.777  - error: Caught by controller[1]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2019-06-24 22:14:46.779  - error: host.raspberrypi instance system.adapter.yahka.1 terminated with code 6 (uncaught exception)
```

I started it again and this is the first errors. The above one was after a few errors.
`

```
2019-06-24 23:03:56.929  - info: host.raspberrypi instance system.adapter.yahka.1 started with pid 16952
--
2019-06-24 23:04:02.990  - info: yahka.1 starting. Version 0.9.2 in /opt/iobroker/node_modules/iobroker.yahka, node: v6.11.1
2019-06-24 23:04:03.046  - info: yahka.1 adapter ready, checking config
2019-06-24 23:04:03.125  - info: yahka.1 adding Heimkino with UUID: 117e0000-1d7f-45f8-8d6e-dd36a7f06ab7
2019-06-24 23:04:03.185  - info: yahka.1 adding Netflix with UUID: 0c415412-472a-467b-a38a-8f897848364a
2019-06-24 23:04:03.200  - info: yahka.1 adding Musik with UUID: 7d883b45-7e49-465e-a20d-f2411fd49d77
2019-06-24 23:04:03.208  - info: yahka.1 adding Küchenlampe with UUID: fd33b409-77c0-4b4d-9263-8e2fa30adc18
2019-06-24 23:04:03.239  - info: yahka.1 adding PS4 with UUID: 0b8a305f-d785-4a21-9117-8d385870b923
2019-06-24 23:04:03.245  - info: yahka.1 adding LED with UUID: c18760d5-3ae2-4309-bfce-00856eb1fe54
2019-06-24 23:04:03.262  - info: yahka.1 adding LED WW with UUID: e4f20e71-ebfd-4745-b465-495163051725
2019-06-24 23:04:03.277  - info: yahka.1 adding TV with UUID: 2301838f-27c7-40b9-930b-3a5c6d4ca93c
2019-06-24 23:04:03.327  - info: yahka.1 adding Youtube with UUID: fb7620ba-3344-4b91-9b35-ff157b82f37a
2019-06-24 23:04:05.476  - error: yahka.1 uncaught exception: "list" argument must be an Array of Buffers
2019-06-24 23:04:05.483  - error: yahka.1 TypeError: "list" argument must be an Array of Buffers
at Function.Buffer.concat (buffer.js:314:13)
at Object.encode (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
at Object.encode (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
at HAPServer._handlePairVerifyStepOne  (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
at HAPServer._handlePairVerify (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
at HAPServer. (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
at emitNone (events.js:86:13)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
2019-06-24 23:04:05.489  - info: yahka.1 cleaning up ...
2019-06-24 23:04:05.491  - info: yahka.1 cleaned up ...
2019-06-24 23:04:05.642  - error:  Caught by controller[0]: HAP Warning: Characteristic  00000008-0000-1000-8000-0026BB765291 not in required or optional  characteristics for service 00000049-0000-1000-8000-0026BB765291. Adding  anyway.
2019-06-24 23:04:05.644  - error: Caught by controller[1]: TypeError: "list" argument must be an Array of Buffers
2019-06-24 23:04:05.645  - error: Caught by controller[1]:     at Function.Buffer.concat (buffer.js:314:13)
2019-06-24 23:04:05.646  - error:  Caught by controller[1]:     at Object.encode  (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
2019-06-24 23:04:05.647  - error:  Caught by controller[1]:     at Object.encode  (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
2019-06-24 23:04:05.647  - error:  Caught by controller[1]:     at HAPServer._handlePairVerifyStepOne  (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
2019-06-24 23:04:05.648  - error:  Caught by controller[1]:     at HAPServer._handlePairVerify  (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
2019-06-24 23:04:05.649  - error: Caught by controller[1]:     at HAPServer. (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
2019-06-24 23:04:05.649  - error: Caught by controller[1]:     at emitNone (events.js:86:13)
2019-06-24 23:04:05.650  - error: Caught by controller[1]:     at IncomingMessage.emit (events.js:185:7)
2019-06-24 23:04:05.650  - error: Caught by controller[1]:     at endReadableNT (_stream_readable.js:974:12)
2019-06-24 23:04:05.651  - error: Caught by controller[1]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2019-06-24 23:04:05.652  - error: host.raspberrypi instance system.adapter.yahka.1 terminated with code 0 (OK)
2019-06-24 23:04:05.653  - info: host.raspberrypi Restart adapter system.adapter.yahka.1 because enabled
```

`

`

**Comment by nicoh88** [comment]
Too old. 0.11.0 in ioBroker Repo.
