### ISSUE TITLE
Error in docker container

### ISSUE THREAD

**Issue by EbSe** [jensweigele/ioBroker.yahka#173]
Hallo,

beim Starten des Adapters bekomme ich folgenden Fehler:

2020-04-20 21:10:23.208  - [31merror[39m: yahka.0 (28886) Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:498:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:369:19)
    at LocalStorage.parseDirSync (/opt/iobroker/node_modules/node-persist/src/local-storage.js:637:35)
    at LocalStorage.parseDataDirSync (/opt/iobroker/node_modules/node-persist/src/local-storage.js:572:21)
    at LocalStorage.initSync (/opt/iobroker/node_modules/node-persist/src/local-storage.js:145:14)
    at Object.nodePersist.initSync (/opt/iobroker/node_modules/node-persist/src/node-persist.js:41:29)
    at Object.init (/opt/iobroker/node_modules/hap-nodejs/index.js:31:13)
    at Object.initHAP (/opt/iobroker/node_modules/iobroker.yahka/main.js:2971:9)
    at TIOBrokerAdapter../yahka.ioBroker-adapter.ts.TIOBrokerAdapter.adapterReady (/opt/iobroker/node_modules/iobroker.yahka/main.js:3351:18)

Adapter version 0.11.0

**Comment by nicoh88** [comment]
@EbSe Konntest du mittlerweile das Problem lösen? Wenn ja, wie?

**Comment by nicoh88** [comment]
Leider, keine Antwort. Schließe Issue!  
Unfortunately, no answer. Close Issue!
