### ISSUE TITLE
Error since Version 0.12.0

### ISSUE THREAD

**Issue by schmupu** [jensweigele/ioBroker.yahka#214]
Since version 0.12.0 Ih get following error:

```
2020-12-28 10:34:36.236  - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-12-28 10:34:36.236  - error: yahka.0 (251712) unhandled promise rejection: Cannot read property '0' of undefined
2020-12-28 10:34:36.282  - error: yahka.0 (251712) TypeError: Cannot read property '0' of undefined
```

Debug Output ( node main.js  --debug )
```
2020-12-28 10:46:52.418  - info: yahka.0 (285587) adding Feinstaub with UUID: 2a2143ec-36b1-42e8-a466-ecb60ddbfb48
2020-12-28 10:46:52.418  - debug: yahka.0 (285587) [Feinstaub] adding Service Feinstaub
2020-12-28 10:46:52.421  - debug: yahka.0 (285587) added subscription for: [state]luftdaten.0.12491.SDS_P1
2020-12-28 10:46:52.421  - debug: yahka.0 (285587) reading state from ioBroker [luftdaten.0.12491.SDS_P1]
2020-12-28 10:46:52.422  - debug: yahka.0 (285587) added subscription for: [state]luftdaten.0.12491.SDS_P2
2020-12-28 10:46:52.422  - debug: yahka.0 (285587) reading state from ioBroker [luftdaten.0.12491.SDS_P2]
2020-12-28 10:46:52.424  - debug: yahka.0 (285587) added subscription for: [state]luftdaten.0.12491.SDS_P1
2020-12-28 10:46:52.424  - debug: yahka.0 (285587) added subscription for: [state]luftdaten.0.12491.SDS_P2
2020-12-28 10:47:23.825  - debug: yahka.0 (287123) [TIoBrokerInOutFunctionMultiState] fromIOBroker event - delivering cached value (undefined)
2020-12-28 10:47:23.836  - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch 
block, or by rejecting a promise which was not handled with .catch().
2020-12-28 10:47:23.837  - error: yahka.0 (287123) unhandled promise rejection: Cannot read property '0' of undefined
2020-12-28 10:47:23.894  - error: yahka.0 (287123) TypeError: Cannot read property '0' of undefined
    at TIoBrokerConversion_Script.eval [as toHKFunction] (eval at TIoBrokerConversion_Script (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.funct
ions/conversion.script.ts:34:29), <anonymous>:1:26)
    at TIoBrokerConversion_Script../yahka.functions/conversion.script.ts.TIoBrokerConversion_Script.toHomeKit (/opt/iobroker/node_modules/iobroker.yahka/web
pack:/yahka.functions/conversion.script.ts:39:29)
    at /opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.homekit-service.ts:156:46
    at TIoBrokerInOutFunction_MultiState../yahka.functions/iofunc.base.ts.TIoBrokerInOutFunctionBase.fromIOBroker (/opt/iobroker/node_modules/iobroker.yahka
/webpack:/yahka.functions/iofunc.base.ts:12:9)
    at YahkaServiceInitializer../yahka.homekit-service.ts.YahkaServiceInitializer.getValueFromIOBroker (/opt/iobroker/node_modules/iobroker.yahka/webpack:/y
ahka.homekit-service.ts:155:23)
    at YahkaServiceInitializer../yahka.homekit-service.ts.YahkaServiceInitializer.initCharacteristic (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yah
ka.homekit-service.ts:113:14)
    at YahkaServiceInitializer../yahka.homekit-service.ts.YahkaServiceInitializer.initService (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.home
kit-service.ts:55:18)
    at YahkaServiceInitializer../yahka.homekit-service.ts.YahkaServiceInitializer.initServices (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.hom
ekit-service.ts:21:18)
    at THomeKitBridge../yahka.homekit-bridge.ts.THomeKitBridge.createDevice (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.homekit-bridge.ts:119:
33)
    at _loop_1 (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.homekit-bridge.ts:44:40)
2020-12-28 10:47:23.894  - info: yahka.0 (287123) cleaning up ...
2020-12-28 10:47:23.895  - info: yahka.0 (287123) cleaned up ...
```
System Information:
Node: v12.19.0
NPM:  6.14.8
JS-Controller:   3.1.6
OS: Linux (Debian)

If I change back to version 0.11.0 everything works fine again.

**Comment by schmupu** [comment]
I could fixed it. I deactivate the yahka device AirQualitySensor (Feinstaub). Now it works.
