### ISSUE TITLE
Crash Loop

### ISSUE THREAD

**Issue by tommyguuuun** [jensweigele/ioBroker.yahka#323]
Hi There,
since a few weeks my YAHKA installation crashes on daily bases. I really don't know how to solve this, but it's very frustrating...

My iOBroker Log tells the following:

`<html>
<body>

yahka.0 | 2022-01-20 17:37:09.103 | error | Exception-Code: ENETUNREACH: send ENETUNREACH 224.0.0.251:5353
-- | -- | -- | --
yahka.0 | 2022-01-20 17:37:09.103 | error | Error: send ENETUNREACH 224.0.0.251:5353 at doSend (dgram.js:714:16) at defaultTriggerAsyncIdScope (internal/async_hooks.js:452:18) at afterDns (dgram.js:660:5) at processTicksAndRejections (internal/process/task_queues.js:83:21)
yahka.0 | 2022-01-20 17:37:09.102 | error | uncaught exception: send ENETUNREACH 224.0.0.251:5353
yahka.0 | 2022-01-20 17:37:09.100 | error | Exception-Code: ENETUNREACH: send ENETUNREACH 224.0.0.251:5353
yahka.0 | 2022-01-20 17:37:09.099 | error | Error: send ENETUNREACH 224.0.0.251:5353 at doSend (dgram.js:714:16) at defaultTriggerAsyncIdScope (internal/async_hooks.js:452:18) at afterDns (dgram.js:660:5) at processTicksAndRejections (internal/process/task_queues.js:83:21)
yahka.0 | 2022-01-20 17:37:09.094 | error | uncaught exception: send ENETUNREACH 224.0.0.251:5353

</body>
</html>` 

and then 

`<html>
<body>

host.iobroker | 2022-01-20 17:37:09.778 | error | instance system.adapter.yahka.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --

</body>
</html>`

Could someone help me out with this?

**Comment by jensweigele** [comment]
Looks like the network/adapter for 224.0.0.251 is not reachable/available. Did you bind an adapter to this IP? Did you change something in your network configuration?

**Comment by tommyguuuun** [comment]
Still no idea? It drives me crazy, as Yahka crashes nearly every two hours…

As i could find out the IP belongs to mDNS, so Multicast, which is used to discover new devices.

**Comment by jensweigele** [comment]
Have you tried to enable the "legacyAdvertiser"?

**Comment by andiweli** [comment]
Hello! 
I have exactly the same issue... my whole LAN is based on 10.1.0.xxx IPs, so theres no 224.0.0.251 IP.
Any solution so far? Had to reboot twice today, then it works for a few hours.
