### ISSUE TITLE
terminated with code 6 (UNCAUGHT_EXCEPTION) -> Cannot read properties of null (reading 'val')

### ISSUE THREAD

**Issue by mimeie** [jensweigele/ioBroker.yahka#452]
Hallo

Heute ging auf einmal Yahka nicht mehr, habe es viele Monate intensiv und ohne Probleme gebraucht. Ich habe dann zur Sicherheit sämtliche Updates von IoBroker, js-controller, yahka, etc. gefahren. Aktuell hänge ich an diesen Logmeldungen fest und weiss nicht weiter.

<html>
<body>

host.jportal1 | 2023-10-09 23:25:12.265 | error | instance system.adapter.yahka.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
yahka.0 | 2023-10-09 23:25:12.041 | info | terminating
yahka.0 | 2023-10-09 23:25:11.539 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
yahka.0 | 2023-10-09 23:25:11.538 | info | terminating
yahka.0 | 2023-10-09 23:25:11.537 | info | cleaned up ...
yahka.0 | 2023-10-09 23:25:11.537 | info | cleaning up ...
yahka.0 | 2023-10-09 23:25:11.508 | error | Cannot read properties of null (reading 'val')
yahka.0 | 2023-10-09 23:25:11.508 | error | TypeError: Cannot read properties of null (reading 'val') at TIoBrokerInOutFunction_Homematic_Dimmer_On.cacheChanged (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.functions/iofunc.homematic.dimmer.ts:38:39) at TIoBrokerInOutFunction_Homematic_Dimmer_On.subscriptionEvent (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.functions/functions.base.ts:61:14) at changeInterceptor (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.ioBroker-adapter.ts:145:75) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.ioBroker-adapter.ts:160:21) at processImmediate (node:internal/timers:478:21)
yahka.0 | 2023-10-09 23:25:11.505 | error | uncaught exception: Cannot read properties of null (reading 'val')

</body>
</html>

Danke für eure Hilfe

**Comment by mimeie** [comment]
meanwhile i've tried every available version of yahka, it is everywhere the same issue

**Comment by mimeie** [comment]
Problem auf sehr seltsame Art und Weise gelöst. [https://forum.iobroker.net/topic/69031/yahka-adapter-terminated-with-code-6-uncaught_exception/13](url)

Muss wahrscheinlich nachbearbeitet werden
