### ISSUE TITLE
Some Yakah Instances not working after js-controller upgrade to 5.x.x

### ISSUE THREAD

**Issue by lehmann-maker** [jensweigele/ioBroker.yahka#461]
Hi there,

one of my instances is not working as soon as I upgrade the js-controller from 4.x.x to any version of 5.x.x. Errors are printed here. I need to upgrade to 5.x.x to work with vis-2 Adapter. Thank you for answers.

YAKAH v. 1.0.3
admin v. 6.13.3
npm v. 10.4.0
Nde.js v. 18.17.1
js-controller v. 5.0.17

host.NAS
2024-01-27 10:41:31.525 warn Do not restart adapter system.adapter.yahka.0 because restart loop detected
host.NAS
2024-01-27 10:41:31.525 info Restart adapter system.adapter.yahka.0 because enabled
host.NAS
2024-01-27 10:41:31.524 error instance system.adapter.yahka.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.NAS
2024-01-27 10:41:31.524 error Caught by controller[15]: [Yahka-0 DAC7@Szene Weihnachten@Szene@On] characteristic value expected boolean and received undefined
host.NAS
2024-01-27 10:41:31.524 error Caught by controller[14]: [Yahka-0 DAC7@Szene Weihnachten@Szene@On] characteristic value expected boolean and received undefined
host.NAS
2024-01-27 10:41:31.524 error Caught by controller[13]: [Yahka-0 DAC7@Szene Ankommen@Szene@On] characteristic value expected boolean and received undefined
host.NAS
2024-01-27 10:41:31.524 error Caught by controller[12]: [Yahka-0 DAC7@Szene Ankommen@Szene@On] characteristic value expected boolean and received undefined
host.NAS
2024-01-27 10:41:31.523 error Caught by controller[11]: [Yahka-0 DAC7@Szene Guten Morgen@Szene@On] characteristic value expected boolean and received undefined
host.NAS
2024-01-27 10:41:31.523 error Caught by controller[10]: [Yahka-0 DAC7@Szene Guten Morgen@Szene@On] characteristic value expected boolean and received undefined
host.NAS
2024-01-27 10:41:31.523 error Caught by controller[9]: [Yahka-0 DAC7@Szene Gute Nacht@Szene@On] characteristic value expected boolean and received undefined
host.NAS
2024-01-27 10:41:31.523 error Caught by controller[8]: [Yahka-0 DAC7@Szene Gute Nacht@Szene@On] characteristic value expected boolean and received undefined
host.NAS
2024-01-27 10:41:31.523 error Caught by controller[7]: [Yahka-0 DAC7@Szene TV@Szene@On] characteristic value expected boolean and received undefined
host.NAS
2024-01-27 10:41:31.522 error Caught by controller[6]: [Yahka-0 DAC7@Szene TV@Szene@On] characteristic value expected boolean and received undefined
host.NAS
2024-01-27 10:41:31.522 error Caught by controller[5]: [Yahka-0 DAC7@Szene Kochen@Szene@On] characteristic value expected boolean and received undefined
host.NAS
2024-01-27 10:41:31.522 error Caught by controller[4]: [Yahka-0 DAC7@Szene Kochen@Szene@On] characteristic value expected boolean and received undefined
host.NAS
2024-01-27 10:41:31.522 error Caught by controller[3]: [Yahka-0 DAC7@Bad Eltern LED@LED Controller@Brightness] characteristic value expected valid finite number and received "undefined" (undefined)
host.NAS
2024-01-27 10:41:31.522 error Caught by controller[2]: [Yahka-0 DAC7@Treppe Spots@Dimmer@Brightness] characteristic value expected valid finite number and received "undefined" (undefined)
host.NAS
2024-01-27 10:41:31.521 error Caught by controller[1]: [Yahka-0 DAC7@Flur Temperatur@Temperatur@Current Temperature] characteristic value expected valid finite number and received "undefined" (undefined)
host.NAS
2024-01-27 10:41:31.521 error Caught by controller[0]: [Yahka-0 DAC7] The selected advertiser, "avahi", isn't available on this platform. Reverting to "bonjour-hap"

yahka.0
2024-01-27 10:41:30.949 warn Terminated (UNCAUGHT_EXCEPTION): Without reason

yahka.0
2024-01-27 10:41:30.948 info terminating

yahka.0
2024-01-27 10:41:30.947 info cleaned up ...

yahka.0
2024-01-27 10:41:30.947 info cleaning up ...

yahka.0
2024-01-27 10:41:30.896 error Error The pattern "[object Object]" is not a valid ID pattern

yahka.0
2024-01-27 10:41:30.895 error ReplyError: Error The pattern "[object Object]" is not a valid ID pattern at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12) at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)

yahka.0
2024-01-27 10:41:30.893 error unhandled promise rejection: Error The pattern "[object Object]" is not a valid ID pattern

yahka.0
2024-01-27 10:41:30.893 error Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by Baenker** [comment]
Du solltest vielleicht mal etwas aufräumen. Du hast viele Szenen die alle nicht das an Yahka senden was es erwartet.

„ expected boolean and received undefined“

Und dann hast Du noch einen Datenpunkt angelgt der keine gültige ID liefert.

Für beides kann der Adapter eher weniger

**Comment by lehmann-maker** [comment]
Hi, hat alles nichts mit dem beschrieben Fehler zu tun, aber dennoch danke. Ich habe mittlerweile alles neu aufgesetzt und es läuft wieder. Issue wird geschlossen.
