### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by DocUltra** [jensweigele/ioBroker.yahka#47]
Hi 
I got some errors, I hope you can help me?

```
host.QNAP253A | 2018-03-19 20:40:09.577 | error | instance system.adapter.yahka.0 terminated with code 0 (OK)
-- | -- | -- | --
host.QNAP253A | 2018-03-19 20:40:09.577 | error | Caught by controller[105]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.alive",{"val":false,"ack":true,"from":"system.adap
host.QNAP253A | 2018-03-19 20:40:09.577 | error | Caught by controller[104]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:socket emitting packet with ack id 4
host.QNAP253A | 2018-03-19 20:40:09.551 | error | Caught by controller[103]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:socket calling ack 2 with [null,"system.adapter.yahka.0.alive"]
host.QNAP253A | 2018-03-19 20:40:09.551 | error | Caught by controller[102]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket socket receive: type "message", data "32[null,"system.adapter.yahka.0.alive"]"
host.QNAP253A | 2018-03-19 20:40:09.551 | error | Caught by controller[101]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager writing packet {"type":2,"data":["getStates",["system.adapter.admin.0.logging"]],"options":{"compress":true},"id":3,"n
host.QNAP253A | 2018-03-19 20:40:09.550 | error | Caught by controller[100]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:socket emitting packet with ack id 3
host.QNAP253A | 2018-03-19 20:40:09.550 | error | Caught by controller[99]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:socket calling ack 1 with [null,["system.adapter.admin.0.logging"]]
host.QNAP253A | 2018-03-19 20:40:09.550 | error | Caught by controller[98]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket socket receive: type "message", data "31[null,["system.adapter.admin.0.logging"]]"
host.QNAP253A | 2018-03-19 20:40:09.550 | error | Caught by controller[97]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket flushing 11 packets in socket
host.QNAP253A | 2018-03-19 20:40:09.550 | error | Caught by controller[96]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.alive",{"val":false,"ack":true,"from":"system.adapt
host.QNAP253A | 2018-03-19 20:40:09.550 | error | Caught by controller[95]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:socket emitting packet with ack id 2
host.QNAP253A | 2018-03-19 20:40:09.550 | error | Caught by controller[94]: at EventedHTTPServer.emit (events.js:188:7) errorCode: -65537 }
host.QNAP253A | 2018-03-19 20:40:09.550 | error | Caught by controller[94]: at emitOne (events.js:96:13)
host.QNAP253A | 2018-03-19 20:40:09.550 | error | Caught by controller[94]: at HAPServer._onListening (/opt/iobroker/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
host.QNAP253A | 2018-03-19 20:40:09.550 | error | Caught by controller[94]: at HAPServer.emit (events.js:188:7)
host.QNAP253A | 2018-03-19 20:40:09.550 | error | Caught by controller[94]: at emitOne (events.js:96:13)
host.QNAP253A | 2018-03-19 20:40:09.550 | error | Caught by controller[94]: at Bridge.Accessory._onListening (/opt/iobroker/node_modules/hap-nodejs/lib/Accessory.js:661:20)
host.QNAP253A | 2018-03-19 20:40:09.549 | error | Caught by controller[94]: at Advertiser.startAdvertising (/opt/iobroker/node_modules/hap-nodejs/lib/Advertiser.js:47:30)
host.QNAP253A | 2018-03-19 20:40:09.549 | error | Caught by controller[94]: at Object.create [as createAdvertisement] (/opt/iobroker/node_modules/mdns/lib/advertisement.js:64:10)
host.QNAP253A | 2018-03-19 20:40:09.549 | error | Caught by controller[94]: at new Advertisement (/opt/iobroker/node_modules/mdns/lib/advertisement.js:56:10)
host.QNAP253A | 2018-03-19 20:40:09.549 | error | Caught by controller[94]: at Error (native)
host.QNAP253A | 2018-03-19 20:40:09.549 | error | Caught by controller[94]: { Error: dns service error: unknown
host.QNAP253A | 2018-03-19 20:40:09.549 | error | Caught by controller[93]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager writing packet {"type":2,"data":["subscribe","yahka.0.checkLogging",null],"options":{"compress":true},"nsp":"/"}
host.QNAP253A | 2018-03-19 20:40:09.549 | error | Caught by controller[92]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.outputCount",{"val":8,"ack":true,"from":"system.ada
host.QNAP253A | 2018-03-19 20:40:09.549 | error | Caught by controller[91]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.inputCount",{"val":0,"ack":true,"from":"system.adap
host.QNAP253A | 2018-03-19 20:40:09.549 | error | Caught by controller[90]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.uptime",{"val":1,"ack":true,"from":"system.adapter.
host.QNAP253A | 2018-03-19 20:40:09.549 | error | Caught by controller[89]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.memHeapUsed",{"val":13.49,"ack":true,"from":"system
host.QNAP253A | 2018-03-19 20:40:09.549 | error | Caught by controller[88]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.memHeapTotal",{"val":23.03,"ack":true,"from":"syste
host.QNAP253A | 2018-03-19 20:40:09.548 | error | Caught by controller[87]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.memRss",{"val":46.34,"ack":true,"from":"system.adap
host.QNAP253A | 2018-03-19 20:40:09.548 | error | Caught by controller[86]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.connected",{"val":true,"ack":true,"expire":30,"from
host.QNAP253A | 2018-03-19 20:40:09.548 | error | Caught by controller[85]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.alive",{"val":true,"ack":true,"expire":25,"from":"s
host.QNAP253A | 2018-03-19 20:40:09.548 | error | Caught by controller[84]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager writing packet {"type":2,"data":["subscribe","*.logging",null],"options":{"compress":true},"nsp":"/"}
host.QNAP253A | 2018-03-19 20:40:09.548 | error | Caught by controller[83]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket flushing 1 packets in socket
host.QNAP253A | 2018-03-19 20:40:09.548 | error | Caught by controller[82]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager writing packet {"type":2,"data":["getKeys","*.logging"],"options":{"compress":true},"id":1,"nsp":"/"}
host.QNAP253A | 2018-03-19 20:40:09.548 | error | Caught by controller[81]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:socket emitting packet with ack id 1
host.QNAP253A | 2018-03-19 20:40:09.548 | error | Caught by controller[80]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:socket calling ack 0 with [null,{"_id":"system.adapter.yahka.0","type":"instance","common":{"name":"yahka","version":"0.7.1","n
host.QNAP253A | 2018-03-19 20:40:09.548 | error | Caught by controller[79]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket socket receive: type "message", data "30[null,{"_id":"system.adapter.yahka.0","type":"instance","common":{"name":"yahka"
host.QNAP253A | 2018-03-19 20:40:09.548 | error | Caught by controller[78]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket flushing 1 packets in socket
host.QNAP253A | 2018-03-19 20:40:09.547 | error | Caught by controller[77]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager writing packet {"type":2,"data":["getObject","system.adapter.yahka.0",null],"options":{"compress":true},"id":0,"nsp":"/
host.QNAP253A | 2018-03-19 20:40:09.547 | error | Caught by controller[76]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:socket emitting packet with ack id 0
host.QNAP253A | 2018-03-19 20:40:09.547 | error | Caught by controller[75]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:socket calling ack 0 with [null,{"val":false,"ack":true,"ts":1521488378095,"q":0,"from":"system.host.QNAP253A","lc":15214883780
host.QNAP253A | 2018-03-19 20:40:09.547 | error | Caught by controller[74]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket socket receive: type "message", data "30[null,{"val":false,"ack":true,"ts":1521488378095,"q":0,"from":"system.host.QNAP2
host.QNAP253A | 2018-03-19 20:40:09.547 | error | Caught by controller[73]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket flushing 1 packets in socket
host.QNAP253A | 2018-03-19 20:40:09.547 | error | Caught by controller[72]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling ignoring poll - transport state "paused"
host.QNAP253A | 2018-03-19 20:40:09.547 | error | Caught by controller[71]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket clearing existing transport polling
host.QNAP253A | 2018-03-19 20:40:09.547 | error | Caught by controller[70]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket setting transport websocket
host.QNAP253A | 2018-03-19 20:40:09.547 | error | Caught by controller[69]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket changing transport and sending upgrade packet
host.QNAP253A | 2018-03-19 20:40:09.547 | error | Caught by controller[69]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling paused
host.QNAP253A | 2018-03-19 20:40:09.547 | error | Caught by controller[68]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling pre-pause polling complete
host.QNAP253A | 2018-03-19 20:40:09.546 | error | Caught by controller[67]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager writing packet {"type":2,"data":["getState","system.adapter.yahka.0.alive"],"options":{"compress":true},"id":0,"nsp":"/
host.QNAP253A | 2018-03-19 20:40:09.546 | error | Caught by controller[66]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:socket emitting packet with ack id 0
host.QNAP253A | 2018-03-19 20:40:09.546 | error | Caught by controller[65]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket socket receive: type "message", data "0"
host.QNAP253A | 2018-03-19 20:40:09.546 | error | Caught by controller[64]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling polling got data 2:40
host.QNAP253A | 2018-03-19 20:40:09.546 | error | Caught by controller[63]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling we are currently polling - waiting to pause
host.QNAP253A | 2018-03-19 20:40:09.546 | error | Caught by controller[62]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket pausing current transport "polling"
host.QNAP253A | 2018-03-19 20:40:09.546 | error | Caught by controller[61]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket probe transport "websocket" pong
host.QNAP253A | 2018-03-19 20:40:09.546 | error | Caught by controller[60]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket probe transport "websocket" opened
host.QNAP253A | 2018-03-19 20:40:09.546 | error | Caught by controller[59]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling-xhr xhr data null
host.QNAP253A | 2018-03-19 20:40:09.546 | error | Caught by controller[59]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling-xhr xhr open GET: http://127.0.0.1:9000/socket.io/?EIO=3&transport=polling&t=M8_nhBT&b64=1&sid=UhJHh2pYFBkIa81cAAA5
host.QNAP253A | 2018-03-19 20:40:09.546 | error | Caught by controller[59]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling-xhr xhr poll
host.QNAP253A | 2018-03-19 20:40:09.545 | error | Caught by controller[58]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling polling
host.QNAP253A | 2018-03-19 20:40:09.545 | error | Caught by controller[57]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket creating transport "websocket"
host.QNAP253A | 2018-03-19 20:40:09.545 | error | Caught by controller[56]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket probing transport "websocket"
host.QNAP253A | 2018-03-19 20:40:09.545 | error | Caught by controller[55]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket starting upgrade probes
host.QNAP253A | 2018-03-19 20:40:09.545 | error | Caught by controller[54]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:socket transport is open - connecting
host.QNAP253A | 2018-03-19 20:40:09.545 | error | Caught by controller[53]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager cleanup
host.QNAP253A | 2018-03-19 20:40:09.545 | error | Caught by controller[52]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager open
host.QNAP253A | 2018-03-19 20:40:09.545 | error | Caught by controller[51]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket socket open
host.QNAP253A | 2018-03-19 20:40:09.545 | error | Caught by controller[50]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket socket receive: type "open", data "{"sid":"UhJHh2pYFBkIa81cAAA5","upgrades":["websocket"],"pingInterval":25000,"pingTime
host.QNAP253A | 2018-03-19 20:40:09.545 | error | Caught by controller[50]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling polling got data 97:0{"sid":"UhJHh2pYFBkIa81cAAA5","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}
host.QNAP253A | 2018-03-19 20:40:09.545 | error | Caught by controller[49]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling ignoring poll - transport state "paused"
host.QNAP253A | 2018-03-19 20:40:09.544 | error | Caught by controller[48]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket clearing existing transport polling
host.QNAP253A | 2018-03-19 20:40:09.544 | error | Caught by controller[47]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket setting transport websocket
host.QNAP253A | 2018-03-19 20:40:09.544 | error | Caught by controller[46]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket changing transport and sending upgrade packet
host.QNAP253A | 2018-03-19 20:40:09.544 | error | Caught by controller[45]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling paused
host.QNAP253A | 2018-03-19 20:40:09.544 | error | Caught by controller[44]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling pre-pause polling complete
host.QNAP253A | 2018-03-19 20:40:09.544 | error | Caught by controller[43]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager readyState opening
host.QNAP253A | 2018-03-19 20:40:09.544 | error | Caught by controller[42]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager connect attempt will timeout after 20000
host.QNAP253A | 2018-03-19 20:40:09.544 | error | Caught by controller[41]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket setting transport polling
host.QNAP253A | 2018-03-19 20:40:09.544 | error | Caught by controller[40]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling-xhr xhr data null
host.QNAP253A | 2018-03-19 20:40:09.544 | error | Caught by controller[39]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling-xhr xhr open GET: http://127.0.0.1:9000/socket.io/?EIO=3&transport=polling&t=M8_nhB9&b64=1
host.QNAP253A | 2018-03-19 20:40:09.544 | error | Caught by controller[38]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling-xhr xhr poll
host.QNAP253A | 2018-03-19 20:40:09.543 | error | Caught by controller[37]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling polling
host.QNAP253A | 2018-03-19 20:40:09.543 | error | Caught by controller[36]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket creating transport "polling"
host.QNAP253A | 2018-03-19 20:40:09.543 | error | Caught by controller[35]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager opening http://127.0.0.1:9000
host.QNAP253A | 2018-03-19 20:40:09.543 | error | Caught by controller[34]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager readyState closed
host.QNAP253A | 2018-03-19 20:40:09.543 | error | Caught by controller[33]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client new io instance for http://127.0.0.1:9000
host.QNAP253A | 2018-03-19 20:40:09.543 | error | Caught by controller[32]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:url parse http://127.0.0.1:9000
host.QNAP253A | 2018-03-19 20:40:09.543 | error | Caught by controller[31]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket socket receive: type "message", data "0"
host.QNAP253A | 2018-03-19 20:40:09.543 | error | Caught by controller[31]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling polling got data 2:40
host.QNAP253A | 2018-03-19 20:40:09.543 | error | Caught by controller[30]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling we are currently polling - waiting to pause
host.QNAP253A | 2018-03-19 20:40:09.543 | error | Caught by controller[29]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket pausing current transport "polling"
host.QNAP253A | 2018-03-19 20:40:09.543 | error | Caught by controller[28]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket probe transport "websocket" pong
host.QNAP253A | 2018-03-19 20:40:09.542 | error | Caught by controller[27]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket probe transport "websocket" opened
host.QNAP253A | 2018-03-19 20:40:09.542 | error | Caught by controller[26]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling-xhr xhr data null
host.QNAP253A | 2018-03-19 20:40:09.542 | error | Caught by controller[25]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling-xhr xhr open GET: http://127.0.0.1:9001/socket.io/?EIO=3&transport=polling&t=M8_nhA7&b64=1&sid=UdJmbsrPks3AXJUfAAA4
host.QNAP253A | 2018-03-19 20:40:09.542 | error | Caught by controller[24]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling-xhr xhr poll
host.QNAP253A | 2018-03-19 20:40:09.542 | error | Caught by controller[23]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling polling
host.QNAP253A | 2018-03-19 20:40:09.542 | error | Caught by controller[22]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket creating transport "websocket"
host.QNAP253A | 2018-03-19 20:40:09.542 | error | Caught by controller[21]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket probing transport "websocket"
host.QNAP253A | 2018-03-19 20:40:09.542 | error | Caught by controller[20]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket starting upgrade probes
host.QNAP253A | 2018-03-19 20:40:09.542 | error | Caught by controller[19]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:socket transport is open - connecting
host.QNAP253A | 2018-03-19 20:40:09.542 | error | Caught by controller[18]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager cleanup
host.QNAP253A | 2018-03-19 20:40:09.542 | error | Caught by controller[17]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager open
host.QNAP253A | 2018-03-19 20:40:09.541 | error | Caught by controller[16]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket socket open
host.QNAP253A | 2018-03-19 20:40:09.541 | error | Caught by controller[15]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:socket socket receive: type "open", data "{"sid":"UdJmbsrPks3AXJUfAAA4","upgrades":["websocket"],"pingInterval":25000,"pingTime
host.QNAP253A | 2018-03-19 20:40:09.541 | error | Caught by controller[14]: Mon, 19 Mar 2018 19:40:09 GMT engine.io-client:polling polling got data 97:0{"sid":"UdJmbsrPks3AXJUfAAA4","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}
host.QNAP253A | 2018-03-19 20:40:09.541 | error | Caught by controller[13]: Mon, 19 Mar 2018 19:40:09 GMT socket.io-client:manager readyState opening
```

**Comment by eumats** [comment]
RTFM
-> https://github.com/jensweigele/ioBroker.yahka/wiki/Installation-and-Troubleshooting

**Comment by GermanBluefox** [comment]
Starte dein Sytem komplett neu und benutze js-controller 1.3.0

eumats <notifications@github.com> schrieb am Mo., 19. März 2018, 20:48:
