### ISSUE TITLE
1.0.5 immer noch Admin leer + Fehler

### ISSUE THREAD

**Issue by backfisch88** [jensweigele/ioBroker.yahka#481]
Hallo

Bei mir in 1.0.5 ist der Admin immer noch leer und bekomme diverse Fehler angezeigt

```
<html>
<body>
<!--StartFragment-->
host.iobroker | 2024-08-29 09:29:44.306 | warn | Do not restart adapter system.adapter.yahka.0 because restart loop detected
-- | -- | -- | --
host.iobroker | 2024-08-29 09:29:44.306 | info | Restart adapter system.adapter.yahka.0 because enabled
host.iobroker | 2024-08-29 09:29:44.306 | error | instance system.adapter.yahka.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
yahka.0 | 2024-08-29 09:29:43.759 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
yahka.0 | 2024-08-29 09:29:43.759 | info | terminating
yahka.0 | 2024-08-29 09:29:43.255 | error | [Außen Helligkeit] unknown service type: BatteryService
yahka.0 | 2024-08-29 09:29:43.255 | error | Error: [Außen Helligkeit] unknown service type: BatteryService at YahkaServiceInitializer.initService (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.homekit-service.ts:88:19) at YahkaServiceInitializer.initServices (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.homekit-service.ts:39:18) at THomeKitBridge.createDevice (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.homekit-bridge.ts:125:33) at THomeKitBridge.init (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.homekit-bridge.ts:49:40) at new THomeKitBridge (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.homekit-bridge.ts:23:14) at TIOBrokerAdapter.createHomeKitBridges (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.ioBroker-adapter.ts:83:27) at TIOBrokerAdapter.adapterReady (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.ioBroker-adapter.ts:56:14) at AdapterClass.emit (node:events:519:28) at AdapterClass._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11699:18) at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11677:22
yahka.0 | 2024-08-29 09:29:43.174 | error | unhandled promise rejection: [Außen Helligkeit] unknown service type: BatteryService
yahka.0 | 2024-08-29 09:29:43.174 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
yahka.0 | 2024-08-29 09:29:43.170 | info | adding Außen Helligkeit with UUID: c109d825-174d-41d9-8b04-99b104b105c5
yahka.0 | 2024-08-29 09:29:43.165 | info | adapter ready, checking config
yahka.0 | 2024-08-29 09:29:43.156 | info | starting. Version 1.0.5 (non-npm: jensweigele/ioBroker.yahka#920e531053890434440739dd49880bc21db1e628) in /opt/iobroker/node_modules/iobroker.yahka, node: v20.17.0, js-controller: 6.0.11

<!--EndFragment-->
</body>
</html>
```

**Comment by cracyfloyd** [comment]
Same here. The adapter runs now and i can see in the log, thats al devices are published. but in the adapter self i cant see any device and i can not put a new one.

**Comment by GermanBluefox** [comment]
https://www.iobroker.net/#de/documentation/faq/_040_contibution.md?fehlerindergrafischeoberflchemelden
