### ISSUE TITLE
Update auf 1.0.4 bis 1.0.9 nicht möglich

### ISSUE THREAD

**Issue by Atredis76** [jensweigele/ioBroker.yahka#495]
Iobroker läuft in einer Proxmox VM

Node.js        : v22.9.0
NPM            : 10.8.3

Der Update Prozess läuft nicht durch aufgrund einen unkompatibelen Node version
pam-devel lässt sich nicht Installieren.

Versucht auf alle höheren Versionen zu aktualisieren
1.0.4
1.0.5
1.0.6
1.0.9

Immer die Gleichen Meldungen

```
$ iobroker upgrade yahka@1.0.9 --debug
Update yahka from @1.0.3 to @1.0.9
Installing iobroker.yahka@1.0.9... (System call)
**npm error engine Unsupported enginenpm error engine Not compatible with your version of node/npm: hap-nodejs@1.1.0npm error notsup Not compatible with your version of node/npm: hap-nodejs@1.1.0npm error notsup Required: {"node":"^18 || ^20"}npm error notsup Actual: {"npm":"10.8.3","node":"v22.9.0"}
npm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-09-29T14_54_13_656Z-debug-0.log
Installed the following apt packages: pam-develThese apt packages were already installed: libavahi-compat-libdnssd-dev**
Update "system.adapter.yahka.0"
upload [19] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/css/yahka.admin.css css/yahka.admin.css text/css
upload [18] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-colors.min.css ext/metroui/css/metro-colors.min.css text/css
upload [16] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-responsive.min.css ext/metroui/css/metro-responsive.min.css text/css
upload [14] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-schemes.min.css ext/metroui/css/metro-schemes.min.css text/css
upload [13] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro.min.css ext/metroui/css/metro.min.css text/css
upload [12] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.eot ext/metroui/fonts/metro.eot application/vnd.ms-fontobject
upload [11] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.svg ext/metroui/fonts/metro.svg image/svg+xml
upload [10] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.ttf ext/metroui/fonts/metro.ttf font/ttf
upload [7] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/js/metro.min.js ext/metroui/js/metro.min.js application/javascript
upload [6] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/home_icon_large.png home_icon_large.png image/png
upload [3] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/words.js words.js application/javascript
upload [2] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.admin.js yahka.admin.js application/javascript
upload [1] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.admin.js.map yahka.admin.js.map application/json
upload [0] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.png yahka.png image/png
Process exited with code 0
```

Komplettes Log gemäß Iobroker Log:

```
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@10.8.3
2 info using node@v22.9.0
3 silly config load:file:/usr/lib/node_modules/npm/npmrc
4 silly config load:file:/opt/iobroker/.npmrc
5 silly config load:file:/home/iobroker/.npmrc
6 silly config load:file:/usr/etc/npmrc
7 verbose title npm install iobroker.yahka@1.0.9
8 verbose argv "install" "--save-exact" "iobroker.yahka@1.0.9" "--foreground-scripts"
9 verbose logfile logs-max:10 dir:/home/iobroker/.npm/_logs/2024-09-29T14_54_13_656Z-
10 verbose logfile /home/iobroker/.npm/_logs/2024-09-29T14_54_13_656Z-debug-0.log
11 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
12 silly logfile start cleaning logs, removing 1 files
13 silly logfile done cleaning log files
14 silly idealTree buildDeps
15 silly fetch manifest iobroker.yahka@1.0.9
16 silly packumentCache full:https://registry.npmjs.org/iobroker.yahka cache-miss
17 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules/iobroker.js-controller
18 http fetch GET 200 https://registry.npmjs.org/iobroker.yahka 1044ms (cache revalidated)
19 silly packumentCache full:https://registry.npmjs.org/iobroker.yahka set size:123582 disposed:false
20 silly placeDep ROOT iobroker.yahka@1.0.9 REPLACE for: iobroker.inst@2.0.3 want: 1.0.9
21 silly fetch manifest hap-nodejs@1.1.0
22 silly packumentCache full:https://registry.npmjs.org/hap-nodejs cache-miss
23 silly fetch manifest ip@^2.0.1
24 silly packumentCache full:https://registry.npmjs.org/ip cache-miss
25 http fetch GET 200 https://registry.npmjs.org/ip 71ms (cache revalidated)
26 silly packumentCache full:https://registry.npmjs.org/ip set size:45299 disposed:false
27 http fetch GET 200 https://registry.npmjs.org/hap-nodejs 270ms (cache updated)
28 silly packumentCache full:https://registry.npmjs.org/hap-nodejs set size:undefined disposed:false
29 silly placeDep ROOT hap-nodejs@1.1.0 OK for: iobroker.yahka@1.0.9 want: 1.1.0
30 silly placeDep node_modules/iobroker.yahka ip@2.0.1 OK for: iobroker.yahka@1.0.9 want: ^2.0.1
31 silly fetch manifest debug@^4.3.5
32 silly packumentCache full:https://registry.npmjs.org/debug cache-miss
33 silly fetch manifest tslib@^2.6.3
34 silly packumentCache full:https://registry.npmjs.org/tslib cache-miss
35 silly fetch manifest tweetnacl@^1.0.3
36 silly packumentCache full:https://registry.npmjs.org/tweetnacl cache-miss
37 silly fetch manifest bonjour-hap@^3.8.0
38 silly packumentCache full:https://registry.npmjs.org/bonjour-hap cache-miss
39 silly fetch manifest futoin-hkdf@^1.5.3
40 silly packumentCache full:https://registry.npmjs.org/futoin-hkdf cache-miss
41 silly fetch manifest node-persist@^0.0.12
42 silly packumentCache full:https://registry.npmjs.org/node-persist cache-miss
43 silly fetch manifest @homebridge/ciao@^1.3.0
44 silly packumentCache full:https://registry.npmjs.org/@homebridge%2fciao cache-miss
45 silly fetch manifest @homebridge/dbus-native@^0.6.0
46 silly packumentCache full:https://registry.npmjs.org/@homebridge%2fdbus-native cache-miss
47 http fetch GET 200 https://registry.npmjs.org/tslib 52ms (cache revalidated)
48 silly packumentCache full:https://registry.npmjs.org/tslib set size:104653 disposed:false
49 http fetch GET 200 https://registry.npmjs.org/debug 145ms (cache revalidated)
50 silly packumentCache full:https://registry.npmjs.org/debug set size:188929 disposed:false
51 http fetch GET 200 https://registry.npmjs.org/tweetnacl 150ms (cache revalidated)
52 silly packumentCache full:https://registry.npmjs.org/tweetnacl set size:79790 disposed:false
53 http fetch GET 200 https://registry.npmjs.org/futoin-hkdf 152ms (cache revalidated)
54 silly packumentCache full:https://registry.npmjs.org/futoin-hkdf set size:61772 disposed:false
55 http fetch GET 200 https://registry.npmjs.org/@homebridge%2fdbus-native 205ms (cache revalidated)
56 silly packumentCache full:https://registry.npmjs.org/@homebridge%2fdbus-native set size:29141 disposed:false
57 http fetch GET 200 https://registry.npmjs.org/@homebridge%2fciao 225ms (cache revalidated)
58 silly packumentCache full:https://registry.npmjs.org/@homebridge%2fciao set size:553698 disposed:false
59 http fetch GET 200 https://registry.npmjs.org/bonjour-hap 546ms (cache revalidated)
60 silly packumentCache full:https://registry.npmjs.org/bonjour-hap set size:153888 disposed:false
61 http fetch GET 200 https://registry.npmjs.org/node-persist 639ms (cache revalidated)
62 silly packumentCache full:https://registry.npmjs.org/node-persist set size:91893 disposed:false
63 silly placeDep ROOT @homebridge/ciao@1.3.1 OK for: hap-nodejs@1.1.0 want: ^1.3.0
64 silly placeDep ROOT @homebridge/dbus-native@0.6.0 OK for: hap-nodejs@1.1.0 want: ^0.6.0
65 silly placeDep ROOT bonjour-hap@3.8.0 OK for: hap-nodejs@1.1.0 want: ^3.8.0
66 silly placeDep node_modules/hap-nodejs debug@4.3.7 OK for: hap-nodejs@1.1.0 want: ^4.3.5
67 silly placeDep node_modules/hap-nodejs futoin-hkdf@1.5.3 OK for: hap-nodejs@1.1.0 want: ^1.5.3
68 silly placeDep node_modules/hap-nodejs node-persist@0.0.12 OK for: hap-nodejs@1.1.0 want: ^0.0.12
69 silly placeDep node_modules/hap-nodejs tslib@2.7.0 OK for: hap-nodejs@1.1.0 want: ^2.6.3
70 silly placeDep node_modules/hap-nodejs tweetnacl@1.0.3 OK for: hap-nodejs@1.1.0 want: ^1.0.3
71 silly fetch manifest debug@^4.3.6
72 silly packumentCache full:https://registry.npmjs.org/debug cache-hit
73 silly fetch manifest @homebridge/long@^5.2.1
74 silly packumentCache full:https://registry.npmjs.org/@homebridge%2flong cache-miss
75 silly fetch manifest @homebridge/put@^0.0.8
76 silly packumentCache full:https://registry.npmjs.org/@homebridge%2fput cache-miss
77 silly fetch manifest hexy@^0.3.5
78 silly packumentCache full:https://registry.npmjs.org/hexy cache-miss
79 silly fetch manifest xml2js@^0.6.2
80 silly packumentCache full:https://registry.npmjs.org/xml2js cache-miss
81 silly fetch manifest array-flatten@^3.0.0
82 silly packumentCache full:https://registry.npmjs.org/array-flatten cache-miss
83 silly fetch manifest deep-equal@^2.2.3
84 silly packumentCache full:https://registry.npmjs.org/deep-equal cache-miss
85 silly fetch manifest multicast-dns@^7.2.5
86 silly packumentCache full:https://registry.npmjs.org/multicast-dns cache-miss
87 silly fetch manifest ms@^2.1.3
88 silly packumentCache full:https://registry.npmjs.org/ms cache-miss
89 silly fetch manifest q@~1.1.1
90 silly packumentCache full:https://registry.npmjs.org/q cache-miss
91 http fetch GET 200 https://registry.npmjs.org/array-flatten 51ms (cache revalidated)
92 silly packumentCache full:https://registry.npmjs.org/array-flatten set size:24005 disposed:false
93 http fetch GET 200 https://registry.npmjs.org/multicast-dns 53ms (cache revalidated)
94 silly packumentCache full:https://registry.npmjs.org/multicast-dns set size:79318 disposed:false
95 http fetch GET 200 https://registry.npmjs.org/deep-equal 62ms (cache revalidated)
96 silly packumentCache full:https://registry.npmjs.org/deep-equal set size:70554 disposed:false
97 http fetch GET 200 https://registry.npmjs.org/hexy 69ms (cache revalidated)
98 silly packumentCache full:https://registry.npmjs.org/hexy set size:39118 disposed:false
99 http fetch GET 200 https://registry.npmjs.org/xml2js 77ms (cache revalidated)
100 silly packumentCache full:https://registry.npmjs.org/xml2js set size:198018 disposed:false
101 http fetch GET 200 https://registry.npmjs.org/ms 78ms (cache revalidated)
102 silly packumentCache full:https://registry.npmjs.org/ms set size:84885 disposed:false
103 http fetch GET 200 https://registry.npmjs.org/q 159ms (cache revalidated)
104 silly packumentCache full:https://registry.npmjs.org/q set size:203240 disposed:false
105 http fetch GET 200 https://registry.npmjs.org/@homebridge%2fput 1032ms (cache revalidated)
106 silly packumentCache full:https://registry.npmjs.org/@homebridge%2fput set size:7821 disposed:false
107 http fetch GET 200 https://registry.npmjs.org/@homebridge%2flong 1054ms (cache revalidated)
108 silly packumentCache full:https://registry.npmjs.org/@homebridge%2flong set size:15452 disposed:false
109 silly placeDep node_modules/@homebridge/ciao debug@4.3.7 OK for: @homebridge/ciao@1.3.1 want: ^4.3.6
110 silly placeDep node_modules/@homebridge/ciao tslib@2.7.0 OK for: @homebridge/ciao@1.3.1 want: ^2.6.3
111 silly placeDep ROOT @homebridge/long@5.2.1 OK for: @homebridge/dbus-native@0.6.0 want: ^5.2.1
112 silly placeDep ROOT @homebridge/put@0.0.8 OK for: @homebridge/dbus-native@0.6.0 want: ^0.0.8
113 silly placeDep ROOT hexy@0.3.5 OK for: @homebridge/dbus-native@0.6.0 want: ^0.3.5
114 silly placeDep node_modules/@homebridge/dbus-native xml2js@0.6.2 OK for: @homebridge/dbus-native@0.6.0 want: ^0.6.2
115 silly placeDep node_modules/bonjour-hap array-flatten@3.0.0 OK for: bonjour-hap@3.8.0 want: ^3.0.0
116 silly placeDep ROOT deep-equal@2.2.3 OK for: bonjour-hap@3.8.0 want: ^2.2.3
117 silly placeDep node_modules/bonjour-hap multicast-dns@7.2.5 OK for: bonjour-hap@3.8.0 want: ^7.2.5
118 silly fetch manifest es-get-iterator@^1.1.3
119 silly packumentCache full:https://registry.npmjs.org/es-get-iterator cache-miss
120 silly fetch manifest isarray@^2.0.5
121 silly packumentCache full:https://registry.npmjs.org/isarray cache-miss
122 silly fetch manifest which-collection@^1.0.1
123 silly packumentCache full:https://registry.npmjs.org/which-collection cache-miss
124 silly fetch manifest dns-packet@^5.2.2
125 silly packumentCache full:https://registry.npmjs.org/dns-packet cache-miss
126 http fetch GET 200 https://registry.npmjs.org/es-get-iterator 55ms (cache revalidated)
127 silly packumentCache full:https://registry.npmjs.org/es-get-iterator set size:31765 disposed:false
128 http fetch GET 200 https://registry.npmjs.org/dns-packet 57ms (cache revalidated)
129 silly packumentCache full:https://registry.npmjs.org/dns-packet set size:96184 disposed:false
130 http fetch GET 200 https://registry.npmjs.org/isarray 59ms (cache revalidated)
131 silly packumentCache full:https://registry.npmjs.org/isarray set size:17392 disposed:false
132 http fetch GET 200 https://registry.npmjs.org/which-collection 78ms (cache revalidated)
133 silly packumentCache full:https://registry.npmjs.org/which-collection set size:13607 disposed:false
134 silly placeDep ROOT es-get-iterator@1.1.3 OK for: deep-equal@2.2.3 want: ^1.1.3
135 silly placeDep node_modules/deep-equal isarray@2.0.5 OK for: deep-equal@2.2.3 want: ^2.0.5
136 silly placeDep ROOT which-collection@1.0.2 OK for: deep-equal@2.2.3 want: ^1.0.1
137 silly fetch manifest is-map@^2.0.2
138 silly packumentCache full:https://registry.npmjs.org/is-map cache-miss
139 silly fetch manifest is-set@^2.0.2
140 silly packumentCache full:https://registry.npmjs.org/is-set cache-miss
141 silly fetch manifest stop-iteration-iterator@^1.0.0
142 silly packumentCache full:https://registry.npmjs.org/stop-iteration-iterator cache-miss
143 silly fetch manifest is-map@^2.0.3
144 silly packumentCache full:https://registry.npmjs.org/is-map cache-miss
145 silly fetch manifest is-set@^2.0.3
146 silly packumentCache full:https://registry.npmjs.org/is-set cache-miss
147 silly fetch manifest is-weakmap@^2.0.2
148 silly packumentCache full:https://registry.npmjs.org/is-weakmap cache-miss
149 silly fetch manifest is-weakset@^2.0.3
150 silly packumentCache full:https://registry.npmjs.org/is-weakset cache-miss
151 http fetch GET 200 https://registry.npmjs.org/stop-iteration-iterator 53ms (cache revalidated)
152 silly packumentCache full:https://registry.npmjs.org/stop-iteration-iterator set size:6237 disposed:false
153 http fetch GET 200 https://registry.npmjs.org/is-set 55ms (cache revalidated)
154 silly packumentCache full:https://registry.npmjs.org/is-set set size:16614 disposed:false
155 http fetch GET 200 https://registry.npmjs.org/is-set 54ms (cache revalidated)
156 silly packumentCache full:https://registry.npmjs.org/is-set set size:16614 disposed:false
157 silly packumentCache full:https://registry.npmjs.org/is-set dispose
158 http fetch GET 200 https://registry.npmjs.org/is-weakset 62ms (cache revalidated)
159 silly packumentCache full:https://registry.npmjs.org/is-weakset set size:18811 disposed:false
160 http fetch GET 200 https://registry.npmjs.org/is-map 70ms (cache revalidated)
161 silly packumentCache full:https://registry.npmjs.org/is-map set size:18079 disposed:false
162 http fetch GET 200 https://registry.npmjs.org/is-weakmap 71ms (cache revalidated)
163 silly packumentCache full:https://registry.npmjs.org/is-weakmap set size:15163 disposed:false
164 http fetch GET 200 https://registry.npmjs.org/is-map 71ms (cache revalidated)
165 silly packumentCache full:https://registry.npmjs.org/is-map set size:18079 disposed:false
166 silly packumentCache full:https://registry.npmjs.org/is-map dispose
167 silly placeDep ROOT is-map@2.0.3 OK for: es-get-iterator@1.1.3 want: ^2.0.2
168 silly placeDep ROOT is-set@2.0.3 OK for: es-get-iterator@1.1.3 want: ^2.0.2
169 silly placeDep node_modules/es-get-iterator isarray@2.0.5 OK for: es-get-iterator@1.1.3 want: ^2.0.5
170 silly placeDep ROOT stop-iteration-iterator@1.0.0 OK for: es-get-iterator@1.1.3 want: ^1.0.0
171 silly placeDep ROOT is-weakmap@2.0.2 OK for: which-collection@1.0.2 want: ^2.0.2
172 silly placeDep ROOT is-weakset@2.0.3 OK for: which-collection@1.0.2 want: ^2.0.3
173 silly placeDep node_modules/@homebridge/ciao ms@2.1.3 OK for: debug@4.3.7 want: ^2.1.3
174 silly placeDep node_modules/bonjour-hap dns-packet@5.6.1 OK for: multicast-dns@7.2.5 want: ^5.2.2
175 silly placeDep node_modules/hap-nodejs ms@2.1.3 OK for: debug@4.3.7 want: ^2.1.3
176 silly placeDep node_modules/hap-nodejs q@1.1.2 OK for: node-persist@0.0.12 want: ~1.1.1
177 verbose stack Error: Unsupported engine
177 verbose stack     at checkEngine (/usr/lib/node_modules/npm/node_modules/npm-install-checks/lib/index.js:14:25)
177 verbose stack     at #checkEngineAndPlatform (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:198:11)
177 verbose stack     at Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:184:41)
177 verbose stack     at async Promise.all (index 1)
177 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
177 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:150:5)
177 verbose stack     at async Npm.exec (/usr/lib/node_modules/npm/lib/npm.js:207:9)
177 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli/entry.js:74:5)
178 verbose pkgid hap-nodejs@1.1.0
179 error code EBADENGINE
180 error engine Unsupported engine
181 error engine Not compatible with your version of node/npm: hap-nodejs@1.1.0
182 error notsup Not compatible with your version of node/npm: hap-nodejs@1.1.0
182 error notsup Required: {"node":"^18 || ^20"}
182 error notsup Actual:   {"npm":"10.8.3","node":"v22.9.0"}
183 silly unfinished npm timer reify 1727621654060
184 silly unfinished npm timer reify:loadTrees 1727621654064
185 verbose cwd /opt/iobroker
186 verbose os Linux 6.1.0-25-amd64
187 verbose node v22.9.0
188 verbose npm  v10.8.3
189 verbose exit 1
190 verbose code 1
191 error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-09-29T14_54_13_656Z-debug-0.log
```

**Comment by marcoschmidt79** [comment]
Same problem.

**Comment by unstressable** [comment]
bei mir hat es direkt geklappt.
Habt ihr vorher nodejs auf den neuesten Stand gebracht?
Bei mir 20.18.0

**Comment by unstressable** [comment]
> Bei mir ist Node auf 23.0.0. Ich probiere es mal mit 20.18.0.

Ja bitte.
Ungerade Versionen sind Beta Versionen. Diese sollen wir ohnehin nicht verwenden.

ich empfehle einen Docker Container, dann brauchst du dir um solche Sachen keine Gedanken mehr zu machen, da die ioBroker Umgebung von Experten gebaut wird.

**Comment by marcoschmidt79** [comment]
> > Bei mir ist Node auf 23.0.0. Ich probiere es mal mit 20.18.0.
> 
> Ja bitte. Ungerade Versionen sind Beta Versionen. Diese sollen wir ohnehin nicht verwenden.
> 
> ich empfehle einen Docker Container, dann brauchst du dir um solche Sachen keine Gedanken mehr zu machen, da die ioBroker Umgebung von Experten gebaut wird.

Das ist mir schon klar, meine Homebridges laufen sonst auch im Docker. Aber ioBroker ist schon ewig halt, hatte das mal auf dem Raspi und war froh, dass ich das so als Image von der SD-Karte in ne VM in Unraid packen konnte. 20.18.0 installiert er jedenfalls nicht, weiß der Geier. 

curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
xz: (stdin): Unerwartetes Ende der Eingabe
tar: Unerwartetes Dateiende im Archiv.
tar: Unerwartetes Dateiende im Archiv.
tar: Error is not recoverable: exiting now

**Comment by mcm1957** [comment]
according to original / first üost node 22 is NOT supported.

**Comment by marcoschmidt79** [comment]
> according to original / first post node 22 is NOT supported.
> 
> see #501

Yes, thank you, with 20.18.0 works fine. :-) the node-version 23 is the problem.

**Comment by mcm1957** [comment]
Mainrainer should check dependencies for updates as node 22 is current stable in the meantime. Although ioBroker still recommends node 20.

**Comment by unstressable** [comment]
> > according to original / first post node 22 is NOT supported.
> > see #501
> 
> Yes, thank you, with 20.18.0 works fine. :-) the node-version 23 is the problem.

please close then :)

**Comment by unstressable** [comment]
@Atredis76 close?

**Comment by Atredis76** [comment]
A new Issue with a better topic is open under #501 so this Issue is only for further Informations.
