### ISSUE TITLE
Installation auf MAC

### ISSUE THREAD

**Issue by theo-69** [jensweigele/ioBroker.yahka#54]
Ich bekomme den Adapter auf meinem Mac nicht installiert. 
```
$ ./iobroker add yahka
npm install iobroker.yahka --production --prefix "/Users/k.niermann/Documents/iobroker" (System call)
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp
 ERR! configure error
 
gyp
 ERR! stack Error: `gyp` failed with exit code: 1gyp 
ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp 
ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp
 ERR!
 System Darwin 17.5.0
gyp ERR! 
command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp
 
ERR! 
cwd /Users/k.niermann/Documents/iobroker/node_modules/curve25519-n
gyp
 ERR!
 
node -v v10.0.0
gyp 
ERR! node-gyp -v
 v3.6.2
gyp 
ERR! not ok
 
npm 
ERR! code ELIFECYCLEnpm ERR! errno 1

npm ERR! curve25519-n@1.2.0 install: `node-gyp rebuild`npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the curve25519-n@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


npm ERR! A complete log of this run can be found in:npm ERR!     /Users/k.niermann/.npm/_logs/2018-05-08T20_10_32_113Z-debug.log

host.Kais-Mac-mini.local install adapter yahka
npm install iobroker.yahka --production --prefix "/Users/k.niermann/Documents/iobroker" (System call)
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp
 
ERR! configure error 
gyp 
ERR! stack Error: `gyp` failed with exit code: 1gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp
 ERR! stack     at ChildProcess.emit (events.js:182:13)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)

gyp ERR! System Darwin 17.5.0gyp
 ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/k.niermann/Documents/iobroker/node_modules/curve25519-ngyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

npm 
ERR! code ELIFECYCLEnpm ERR! errno 1

npm
 ERR! curve25519-n@1.2.0 install: `node-gyp rebuild`npm ERR! Exit status 1
npm ERR!
 npm ERR! Failed at the curve25519-n@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


npm ERR! A complete log of this run can be found in:npm ERR!     /Users/k.niermann/.npm/_logs/2018-05-08T20_10_38_471Z-debug.log

host.Kais-Mac-mini.local install adapter yahka
npm install iobroker.yahka --production --prefix "/Users/k.niermann/Documents/iobroker" (System call)
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp
 ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)

gyp ERR! System Darwin 17.5.0gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/k.niermann/Documents/iobroker/node_modules/curve25519-n
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

npm 
ERR! code ELIFECYCLEnpm ERR! errno 1

npm ERR! curve25519-n@1.2.0 install: `node-gyp rebuild`npm 
ERR! Exit status 1
npm ERR! npm ERR! Failed at the curve25519-n@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


npm ERR! A complete log of this run can be found in:npm ERR!     /Users/k.niermann/.npm/_logs/2018-05-08T20_10_45_447Z-debug.log

host.Kais-Mac-mini.local install adapter yahka
ERROR: host.Kais-Mac-mini.local Cannot install yahka
ERROR: process exited with code 13`
```

**Comment by heseifert** [comment]
Laut den ersten Meldungen hast du kein Xcode installiert...

**Comment by theo-69** [comment]
habe ich inzwischen auch bemerkt aber bleibe lieber bei homebridge, läuft bei mir besser....
