### ISSUE TITLE
Adapter installationsprobleme via ioBroker

### ISSUE THREAD

**Issue by HouseFox** [jensweigele/ioBroker.yahka#80]
Hallo,
habe direkt über ioBroker den ioBroker.yahka Adapter installiert. Jedoch mit mäßigem Erfolg...

```
$ ./iobroker upgrade yahka
Update yahka from @0.7.1 to @0.8.2
NPM version: 6.4.1
npm install iobroker.yahka@0.8.2 --production --save --prefix "/opt/iobroker" (System call)
gyp
 WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.14.1"gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/iobroker/node_modules/authenticate-pam/.node-gyp"

../authenticate_pam.cc:30:31: fatal error: security/pam_appl.h: Datei oder Verzeichnis nicht gefunden #include <security/pam_appl.h>
                               ^
compilation terminated.

make: *** [Release/obj.target/authenticate_pam/authenticate_pam.o] Fehler 1
gyp
 ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! 
stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/authenticate-pam
gyp ERR!
 node -v v8.14.1gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 (node_modules/authenticate-pam):npm WARN optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1


npm install --production (System call) in "/opt/iobroker/node_modules/iobroker.yahka"
npm
 WARN deprecated jscs-preset-wikimedia@1.0.1: Deprecated in favour of eslint-config-wikimedia. -- https://phabricator.wikimedia.org/T118941
npm
 WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm
 WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
gyp
 WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.14.1"gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/iobroker/node_modules/iobroker.yahka/node_modules/curve25519-n/.node-gyp"

gyp
 WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.14.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/iobroker/node_modules/iobroker.yahka/node_modules/ed25519-hap/.node-gyp"
npm
 notice created a lockfile as package-lock.json. You should commit this file.
got /opt/iobroker/node_modules/iobroker.yahka/admin
upload [19] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.png yahka.png image/png
Update "system.adapter.yahka.0"
upload [18] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.admin.js.map yahka.admin.js.map application/json
upload [17] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.admin.js yahka.admin.js application/javascript
upload [16] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/words.js words.js application/javascript
upload [15] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/index_m.html index_m.html text/html
upload [14] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/index.html index.html text/html
upload [13] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/home_icon_large.png home_icon_large.png image/png
upload [12] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/js/metro.min.js ext/metroui/js/metro.min.js application/javascript
upload [11] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/selection.json ext/metroui/fonts/selection.json application/json
upload [10] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.woff ext/metroui/fonts/metro.woff application/font-woff
upload [9] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.ttf ext/metroui/fonts/metro.ttf application/x-font-ttf
upload [8] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.svg ext/metroui/fonts/metro.svg image/svg+xml
upload [7] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.eot ext/metroui/fonts/metro.eot application/vnd.ms-fontobject
upload [6] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro.min.css ext/metroui/css/metro.min.css text/css
upload [5] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-schemes.min.css ext/metroui/css/metro-schemes.min.css text/css
upload [4] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-rtl.min.css ext/metroui/css/metro-rtl.min.css text/css
upload [3] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-responsive.min.css ext/metroui/css/metro-responsive.min.css text/css
upload [2] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-icons.min.css ext/metroui/css/metro-icons.min.css text/css
upload [1] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-colors.min.css ext/metroui/css/metro-colors.min.css text/css
upload [0] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/css/yahka.admin.css css/yahka.admin.css text/css
Adapter "yahka" updated
process exited with code 0
```

Wenn ich der Anleitung auf https://github.com/jensweigele/ioBroker.yahka/wiki/Installation-and-Troubleshooting folge dann erhalte ich folgende Meldungen.

```
pi@raspberrypi:~ $ sudo apt-get install libavahi-compat-libdnssd-dev
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
libavahi-compat-libdnssd-dev ist schon die neueste Version (0.6.32-2).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
pi@raspberrypi:~ $ sudo apt-get install avahi-daemon -y
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
avahi-daemon ist schon die neueste Version (0.6.32-2).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
pi@raspberrypi:~ $ sudo nano avahi-daemon.conf
domain-name=local
use-ipv4=yes
use-ipv6=yes
enable-dbus=yes

pi@raspberrypi:~ $ sudo apt-get install pam-devel -y
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
E: Paket pam-devel kann nicht gefunden werden.
pi@raspberrypi:~ $
```

Der Adapter erscheint in in ioBroker und kann auch einen Service hinzufügen. Jedoch nichts auswählen bzw. eintragen.

Kann mir jemand weiterhelfen welches Problem hier vorliegt und was ich falsch gemacht habe.?
Danke Euch.

![iobroker yahka_01](https://user-images.githubusercontent.com/43676945/50458254-f2b5f700-0961-11e9-83ba-31002a28bce3.png)

![iobroker yahka_02](https://user-images.githubusercontent.com/43676945/50458267-05c8c700-0962-11e9-835b-4c7a2f341e09.png)

**Comment by jensweigele** [comment]
`../authenticate_pam.cc:30:31: fatal error: security/pam_appl.h: Datei oder Verzeichnis nicht gefunden #include <security/pam_appl.h>`
-> https://github.com/jensweigele/ioBroker.yahka/wiki/Installation-and-Troubleshooting

**Comment by HouseFox** [comment]
Hallo,
das habe ich aus meinem log auch gelesen. 
```
../authenticate_pam.cc:30:31: fatal error: security/pam_appl.h: Datei oder Verzeichnis nicht gefunden #include <security/pam_appl.h>
-> https://github.com/jensweigele/ioBroker.yahka/wiki/Installation-and-Troubleshooting
```

Ich bekomme jedoch folgende Fehlermeldung bei der Installation von "pam-devel"
Warum diese Fehlermeldung?
```
pi@raspberrypi:~ $ sudo apt-get install pam-devel -y
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
E: Paket pam-devel kann nicht gefunden werden.
pi@raspberrypi:~ $
´´´
