### ISSUE TITLE
Weiterhin adapter installationsprobleme via ioBroker siehe #80

### ISSUE THREAD

**Issue by HouseFox** [jensweigele/ioBroker.yahka#83]
Hallo,
nach wie vor habe ich Probleme rund um die Installation von ioBroker.yahka.
Speziell darum, dass mit "sudo apt-get install pam-devel -y" die Meldung "_E: Paket pam-devel kann nicht gefunden werden_" erscheint.

Warum bekomme ich die folgende Fehlermeldung bei der Installation von "pam-devel" und was muss ich tuen? 

siehe auch Fehler--> https://github.com/jensweigele/ioBroker.yahka/issues/80

Danke für eure Hilfe.

```
../authenticate_pam.cc:30:31: fatal error: security/pam_appl.h: Datei oder Verzeichnis nicht gefunden #include <security/pam_appl.h>
-> https://github.com/jensweigele/ioBroker.yahka/wiki/Installation-and-Troubleshooting
```
```
pi@raspberrypi:~ $ sudo apt-get install pam-devel -y
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
E: Paket pam-devel kann nicht gefunden werden.
pi@raspberrypi:~ $
´´´

**Comment by jensweigele** [comment]
Ungetestet: probier mal 
sudo apt-get install libpam0g-dev

**Comment by HouseFox** [comment]
Hallo,
danke für die Antwort!
Die Installation von _"sudo apt-get install libpam0g-dev"_ scheint funktioniert zu haben, denke ich...
Aber offensichtlich mache ich einen Fehler... Ich bekomme den Adapter nicht zum laufen.
Danke für die Hilfe.

```
Using username "pi".
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sun Dec 30 00:42:58 2018 from 192.168.2.106
pi@raspberrypi:~ $ sudo apt-get install libpam0g-dev
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Die folgenden NEUEN Pakete werden installiert:
  libpam0g-dev
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 177 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 350 kB Plattenplatz zusätzlich benutzt.
Holen:1 http://archive.raspberrypi.org/debian stretch/main armhf libpam0g-dev armhf 1.1.8-3.6+rpi1 [177 kB]
Es wurden 177 kB in 0 s geholt (397 kB/s).
Vormals nicht ausgewähltes Paket libpam0g-dev:armhf wird gewählt.
(Lese Datenbank ... 39072 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../libpam0g-dev_1.1.8-3.6+rpi1_armhf.deb ...
Entpacken von libpam0g-dev:armhf (1.1.8-3.6+rpi1) ...
libpam0g-dev:armhf (1.1.8-3.6+rpi1) wird eingerichtet ...
Trigger für man-db (2.7.6.1-2) werden verarbeitet ...
pi@raspberrypi:~ $
```



Anschließend habe ich das ""Troubleshooting nochmals durchgeführt.
Das zeigt mir aber das alle vorherigen Installationen auf dem neuesten Stand sind.

```
pi@raspberrypi:~ $ sudo apt-get install libavahi-compat-libdnssd-dev
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
libavahi-compat-libdnssd-dev ist schon die neueste Version (0.6.32-2).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
pi@raspberrypi:~ $


pi@raspberrypi:~ $ sudo apt-get install avahi-daemon -y
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
avahi-daemon ist schon die neueste Version (0.6.32-2).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
pi@raspberrypi:~ $


pi@raspberrypi:~ $ sudo nano avahi-daemon.conf
  GNU nano 2.7.4           Datei: avahi-daemon.conf

domain-name=local
use-ipv4=yes
use-ipv6=yes
enable-dbus=yes


pi@raspberrypi:~ $ sudo apt-get install libpam0g-dev
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
libpam0g-dev ist schon die neueste Version (1.1.8-3.6+rpi1).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
pi@raspberrypi:~ $
```

Auch die Installation des Adapters zeigt bis auf "WARN" keinen Error.
Oder ist der "WARN" der Grund dafür das der Adapter bei mir nicht so funktioniert wie vorgesehen?
Im Adapter kann ich zwar bspw "_Lightbulb_" anwählen, jedoch nichts weiter auswählen, siehe Bild.

```
$ ./iobroker add yahka  --host raspberrypi
NPM version: 6.4.1
npm install iobroker.yahka --production --save --prefix "/opt/iobroker" (System call)
gyp
 WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.14.1"gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/iobroker/node_modules/curve25519-n/.node-gyp"

gyp
 WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.14.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/iobroker/node_modules/ed25519-hap/.node-gyp"
host.raspberrypi install adapter yahka
got /opt/iobroker/node_modules/iobroker.yahka/admin
upload [19] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.png yahka.png image/png
upload [18] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.admin.js.map yahka.admin.js.map application/json
upload [17] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.admin.js yahka.admin.js application/javascript
upload [16] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/words.js words.js application/javascript
upload [15] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/index_m.html index_m.html text/html
upload [14] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/index.html index.html text/html
upload [13] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/home_icon_large.png home_icon_large.png image/png
upload [12] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/js/metro.min.js ext/metroui/js/metro.min.js application/javascript
upload [11] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/selection.json ext/metroui/fonts/selection.json application/json
upload [10] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.woff ext/metroui/fonts/metro.woff application/font-woff
upload [9] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.ttf ext/metroui/fonts/metro.ttf application/x-font-ttf
upload [8] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.svg ext/metroui/fonts/metro.svg image/svg+xml
upload [7] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.eot ext/metroui/fonts/metro.eot application/vnd.ms-fontobject
upload [6] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro.min.css ext/metroui/css/metro.min.css text/css
upload [5] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-schemes.min.css ext/metroui/css/metro-schemes.min.css text/css
upload [4] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-rtl.min.css ext/metroui/css/metro-rtl.min.css text/css
upload [3] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-responsive.min.css ext/metroui/css/metro-responsive.min.css text/css
upload [2] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-icons.min.css ext/metroui/css/metro-icons.min.css text/css
upload [1] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-colors.min.css ext/metroui/css/metro-colors.min.css text/css
upload [0] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/css/yahka.admin.css css/yahka.admin.css text/css
host.raspberrypi object system.adapter.yahka created
host.raspberrypi object yahka.meta._serviceDictionary created
host.raspberrypi object yahka.meta._accessoryCategories created
host.raspberrypi object yahka.meta._conversionFunctions created
host.raspberrypi object yahka.meta._inoutFunctions created
host.raspberrypi create instance yahka
host.raspberrypi object system.adapter.yahka.0.outputCount created
host.raspberrypi object system.adapter.yahka.0.inputCount created
host.raspberrypi object system.adapter.yahka.0.uptime created
host.raspberrypi object system.adapter.yahka.0.memRss created
host.raspberrypi object system.adapter.yahka.0.memHeapTotal created
host.raspberrypi object system.adapter.yahka.0.memHeapUsed created
host.raspberrypi object system.adapter.yahka.0.connected created
host.raspberrypi object system.adapter.yahka.0.alive created
host.raspberrypi object system.adapter.yahka.0 created
process exited with code 0
```
![iobroker yahka_03](https://user-images.githubusercontent.com/43676945/50548224-343bf000-0c49-11e9-870c-e88e9aa8230e.png)

**Comment by jensweigele** [comment]
Was sagt den das Logfile in ioBroker?
Die Warn-Meldung deutet auch auf Probleme mit Berechtigungen hin. Hier solltest du dich mal im ioBroker Forum umschauen

**Comment by HouseFox** [comment]
Hi,

ich habe einen Blick in das log geworfen und folgende Error Meldung gefunden.
Was diese Error Meldung nun jedoch im einzelnen bedeutet verstehe ich nicht.
Was meint ihr?

```
2019-01-01 21:33:12.075  - info: host.raspberrypi instance system.adapter.yahka.0 started with pid 6806
--
2019-01-01 21:33:13.552  - info: yahka.0 starting. Version 0.8.2 in /opt/iobroker/node_modules/iobroker.yahka, node: v8.14.1
2019-01-01 21:33:13.569  - info: yahka.0 adapter ready, checking config
2019-01-01 21:33:13.584  - info: yahka.0 adding Licht01 with UUID: 7b54888d-ef82-475f-91b1-bbea67142050
2019-01-01 21:33:13.596  - error: yahka.0 uncaught exception: unknown service type:
2019-01-01 21:33:13.596  - error: yahka.0 Error: unknown service type:
at THomeKitBridge.initService (/opt/iobroker/node_modules/iobroker.yahka/yahka.homekit-bridge.js:80:19)
at THomeKitBridge.createDevice (/opt/iobroker/node_modules/iobroker.yahka/yahka.homekit-bridge.js:74:18)
at THomeKitBridge.init (/opt/iobroker/node_modules/iobroker.yahka/yahka.homekit-bridge.js:24:38)
at new THomeKitBridge (/opt/iobroker/node_modules/iobroker.yahka/yahka.homekit-bridge.js:14:14)
at TIOBrokerAdapter.createHomeKitBridges (/opt/iobroker/node_modules/iobroker.yahka/yahka.ioBroker-adapter.js:52:27)
at TIOBrokerAdapter.adapterReady (/opt/iobroker/node_modules/iobroker.yahka/yahka.ioBroker-adapter.js:29:14)
at emitNone (events.js:106:13)
at Adapter.emit (events.js:208:7)
at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4990:18)
at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:788:29
2019-01-01 21:33:13.597  - info: yahka.0 cleaning up ...
2019-01-01 21:33:13.598  - info: yahka.0 cleaned up ...
2019-01-01 21:33:13.627  - info: yahka.0 terminating
2019-01-01 21:33:13.654  - error: Caught by controller[0]: Error: unknown service type:
2019-01-01 21:33:13.654  - error: Caught by controller[0]:     at THomeKitBridge.initService (/opt/iobroker/node_modules/iobroker.yahka/yahka.homekit-bridge.js:80:19)
2019-01-01 21:33:13.654  - error: Caught by controller[0]:     at THomeKitBridge.createDevice (/opt/iobroker/node_modules/iobroker.yahka/yahka.homekit-bridge.js:74:18)
2019-01-01 21:33:13.655  - error: Caught by controller[0]:     at THomeKitBridge.init (/opt/iobroker/node_modules/iobroker.yahka/yahka.homekit-bridge.js:24:38)
2019-01-01 21:33:13.655  - error: Caught by controller[0]:     at new THomeKitBridge (/opt/iobroker/node_modules/iobroker.yahka/yahka.homekit-bridge.js:14:14)
2019-01-01 21:33:13.655  - error: Caught by controller[0]:     at TIOBrokerAdapter.createHomeKitBridges (/opt/iobroker/node_modules/iobroker.yahka/yahka.ioBroker-adapter.js:52:27)
2019-01-01 21:33:13.655  - error: Caught by controller[0]:     at TIOBrokerAdapter.adapterReady (/opt/iobroker/node_modules/iobroker.yahka/yahka.ioBroker-adapter.js:29:14)
2019-01-01 21:33:13.655  - error: Caught by controller[0]:     at emitNone (events.js:106:13)
2019-01-01 21:33:13.655  - error: Caught by controller[0]:     at Adapter.emit (events.js:208:7)
2019-01-01 21:33:13.655  - error: Caught by controller[0]:     at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4990:18)
2019-01-01 21:33:13.655  - error: Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:788:29
2019-01-01 21:33:13.656  - error: host.raspberrypi instance system.adapter.yahka.0 terminated with code 0 (OK)
2019-01-01 21:33:13.656  - info: host.raspberrypi Restart adapter system.adapter.yahka.0 because enabled
```

**Comment by jensweigele** [comment]
der ausgewählte Service-Type is Yahka nicht bekannt (vermutlich weil der Service-Type = "" ist).

Du hast ein Problem bei deiner Installation - ich denke solange das nicht gelöst ist, wird der Adapter nicht funktionieren.

Schau mal in den Foren nach den Berechtigungsproblemen, das wird bestimmt eine der Ursachen sein.

**Comment by jensweigele** [comment]
@HouseFox : hast du hierzu inzwischen mehr in Erfahrung bringen können?

**Comment by HouseFox** [comment]
@jensweigele : ich habe zu diesem Problem einen Forenbeitrag mit bitte um Hilfe eingerichtet. Leider bis jetzt ohne Antwort darauf. https://forum.iobroker.net/viewtopic.php?f=20&t=20246

**Comment by jensweigele** [comment]
Zwei Sachen fallen mir noch ein:
1. Welchen Browser setzt du ein? (bitte keinen Internet Explorer - nimm FireFox oder Chrome o.ä)
2. Kannst du mal bitte die Developer Console im Browser einschalten (Control+Shift+J unter Windows), auf die YAHKA Konfiguration gehen und dann den Inhalt der Konsole hier posten? (sofern dort Fehlermeldungen zu sehen sind)

**Comment by HouseFox** [comment]
Hallo Jens,
endschuldige bitte die Verzögerung, ich hatte die letzten Tage keine Zeit mich darum zu kümmern.
Aber...
Ich werde noch verrückt! Mit Firefox funktioniert es so wie du es dir erdacht hast.
Super Adapter!!!

Aber eine Rückfrage habe ich dennoch.
Warum funktioniert der Adapter in iobroker nicht mit dem neuen Microsoft Edge Browser???
Ärger mich gerade sowas von...

Vielleicht steht es auch in deiner Beschreibung des Adapters und ich habe es überlesen...
Evtl. fügst du noch einen Hinweis hinzu.

Also Danke erstmal und eine super Adapterarbeit von dir.

Gruß Andreas
