### ISSUE TITLE
Probleme mit Yahka 0.9.0 und BatteryService - keine Funktion

### ISSUE THREAD

**Issue by kugelkopf123** [jensweigele/ioBroker.yahka#93]
Moin! 

Ich habe mich auf Grund der tollen neuen Funktionen in der v.9.0.2 zu einem update verleiten lassen. 

Ein Fehler.
Was unter der v8.2. noch wunderbar lief, produzierte in der neuen Version nur Fehler. 

Die Geräte in der Home App wurden als nicht erreichbar angezeigt.
Schon bei der installation fiel mir der Hinweis auf ein fehlendes "react" hin welches ich via npm nach installiert habe. // Neustart iobroker

Weiterhin waren alle Geräte offline. //Neustart RaspberryPi // Neustart iPhone
Keine Besserung.

Versuchsweise einfach mal den Port von Yahka verändert. Das produzierte folgenden Fehler im Log: 

`2019-01-15 20:44:08.769  - [32minfo[39m: yahka.0 cleaning up ...
2019-01-15 20:44:08.770  - [32minfo[39m: yahka.0 cleaned up ...
2019-01-15 20:44:09.773  - [32minfo[39m: yahka.0 cleaning up ...
2019-01-15 20:44:10.950  - [31merror[39m: Caught by controller[0]: HAP Warning: Characteristic 00000073-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000049-0000-1000-8000-0026BB765291. Adding anyway.
2019-01-15 20:44:10.951  - [31merror[39m: Caught by controller[1]: { Error: listen EACCES 0.0.0.0:1
2019-01-15 20:44:10.952  - [31merror[39m: Caught by controller[1]:     at Server.setupListenHandle [as _listen2] (net.js:1343:19)
2019-01-15 20:44:10.952  - [31merror[39m: Caught by controller[1]:     at listenInCluster (net.js:1401:12)
2019-01-15 20:44:10.952  - [31merror[39m: Caught by controller[1]:     at Server.listen (net.js:1485:7)
2019-01-15 20:44:10.952  - [31merror[39m: Caught by controller[1]:     at EventedHTTPServer.listen (/opt/iobroker/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
2019-01-15 20:44:10.952  - [31merror[39m: Caught by controller[1]:     at HAPServer.listen (/opt/iobroker/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
2019-01-15 20:44:10.953  - [31merror[39m: Caught by controller[1]:     at Bridge.Accessory.publish (/opt/iobroker/node_modules/hap-nodejs/lib/Accessory.js:607:16)
2019-01-15 20:44:10.953  - [31merror[39m: Caught by controller[1]:     at THomeKitBridge../yahka.homekit-bridge.ts.THomeKitBridge.init (/opt/iobroker/node_modules/iobroker.yahka/main.js:1562:27)
2019-01-15 20:44:10.953  - [31merror[39m: Caught by controller[1]:     at new THomeKitBridge (/opt/iobroker/node_modules/iobroker.yahka/main.js:1533:14)
2019-01-15 20:44:10.953  - [31merror[39m: Caught by controller[1]:     at TIOBrokerAdapter../yahka.ioBroker-adapter.ts.TIOBrokerAdapter.createHomeKitBridges (/opt/iobroker/node_modules/iobroker.yahka/main.js:2140:27)
2019-01-15 20:44:10.953  - [31merror[39m: Caught by controller[1]:     at TIOBrokerAdapter../yahka.ioBroker-adapter.ts.TIOBrokerAdapter.adapterReady (/opt/iobroker/node_modules/iobroker.yahka/main.js:2117:14)
2019-01-15 20:44:10.953  - [31merror[39m: Caught by controller[1]:   errno: 'EACCES',
2019-01-15 20:44:10.953  - [31merror[39m: Caught by controller[1]:   code: 'EACCES',
2019-01-15 20:44:10.954  - [31merror[39m: Caught by controller[1]:   syscall: 'listen',
2019-01-15 20:44:10.954  - [31merror[39m: Caught by controller[1]:   address: '0.0.0.0',
2019-01-15 20:44:10.954  - [31merror[39m: Caught by controller[1]:   port: 1 }
2019-01-15 20:44:10.954  - [31merror[39m: host.raspi3 instance system.adapter.yahka.0 terminated with code 6 (uncaught exception)
2019-01-15 20:44:10.954  - [32minfo[39m: host.raspi3 Restart adapter system.adapter.yahka.0 because enabled`

Und führte zu nichts. Also wieder zurück auf 0.

Inzw. waren mir die Ideen ausgegangen, deshalb fügte ich einen weiteren Yahka Adapter hinzu. Instanz: 1. 
Ich erstellte in Ihr eine Lightbulb nur mit der ON Eigenschaft und fügte diese Bridge dann in der Homeapp als ein weiteres Zuhause hinzu. Das funktionierte überraschend. 
Mutig probierte ich auch CT und BRI dazu aus. Auch das funktionierte weiterhin. 
Weiterhin fügte ich einen meiner Sensoren hinzu. Bewegungsmelder von Aqara PIR-Sensor. Als Service: MotionSensor, Lightsensor, BatteryService.

Plötzlich ging nichts mehr. Jedes Gerät zeigte in der Home-App "Nicht verfügbar" an. 
Also.. Neustart iPhone, Neustart Raspberrypi.
Keine Besserung. 
Die Bridge aus dem Zuhause gelöscht und versucht neu Hinzuzufügen. Nicht möglich. In der Vergangenheit hat es ab und zu geholfen den Benutzernamen der Bridge im Adapter zu ändern (die MAC -Adresse). Also tat ich dies. Auch das half nicht. 
Ich deaktivierte den BWM im Adapter, änderte wieder die MAC-Adresse und plötzlich war es möglich die Bridge in der Home-App hinzuzufügen. 

Alle Geräte waren online. // Neustart aller Geräte

Immer noch alles da!

BWM wieder aktivieren. 
Gleiche Fehlerbild. Alle Geräte wieder auf "Nicht verfügbar".

BWM wieder deaktiviert. > Alles neugestartet. Weiterhin "Nicht verfügbar"

Bridge gelöscht und wieder neu hinzugefügt. Alles läuft wieder. 

Den Service BatteryService aus dem BWM gelöscht und BWM aktiviert.

BWM wird angezeigt in der HomeApp. Weiterhin funktioniert alles. 

Offensichtlich verträgt sich der BatteryService also nicht.

Das könnte man noch verkraften, wenn denn nicht dadurch jedesmal ein heiden Aufwand betrieben werden müsste um bei einer fehlerhaften Eingabe oder eines Fehlerhaften Services, alles neu Installiert werden muss. 

Mit der Erfahrung wechselte ich wieder zur alten Instanz 0 die noch alle Geräte inne hat.
Ich deaktivierte jedes Gerät welches einen BatteryService hat. Keine Besserung. Ich deaktivierte alle Geräte. Auch keine Besserung. Es bleibt hier bei "Keine Antwort". 

Das ist ziemlich nervig, denn ich habe doch inzw. eine beachtliche Menge an Schaltern und Sensoren in dem Adapter. 

Hier eine kurze Zusammenfassung der Geräte und den verwendeten Services im Adapter:

1. 8x Aqara Temp/Luftfeuchte/Luftdruck Sensor mit: TempSensor,HumiditiySensor,BatteryService
2. 6x Aqara ContactSensor mit: ContactSensor, BatteryService
3. 4x Aqara PIR BWM mit: MotionSensor,LightSensor,BatteryService
4. 5x div. TempSensoren des NAS mit: TempSensor
5. 8x Osram Smart+ Plugs mit: Outlet
6. 3x Comet Heizkörper Thermostat mit: Thermostat, BatteryService
7. 4x div. Schalter zum setzen von Datenpunkten in ioBroker mit: Switch

Log mässig ist nichts auffällig. Auch im Debugmode des Adapters fällt mir im Vergleich nichts auf was anders ist. 
Als letzten Test, löschte ich in der Instanz 1 noch einmal den BWM komplett und deaktivierte ihn nicht nur. Dennoch keine Änderung. Es bleib auch jetzt weiterhin bei "Nicht verfügbar" bei allen Geräten in der Home app. 
Jetzt müsste man also wieder die Bridge entfernen, und diese dann wieder hinzufügen.

Übrigens. Solange der "defekte" BatteryService sich in der Geräteliste befindet, ist es nicht möglich die Bridge hinzuzufügen. Erst wenn man ihn rauslöscht lässt sich die Bridge neu hinzufügen.

Woran kann das alles liegen? Habt ihr ähnliche Probleme?

Grüße!

**Comment by jensweigele** [comment]
Kannst du die fehlerhafte Konfiguration hier posten? Ich würde das gerne mal nachvollziehen.

Wenn die Geräte nicht mehr erreichbar sind, hilft oft das ändern des Usernames - dann muss die Bridge aber wieder neu gepaart werden

**Comment by kugelkopf123** [comment]
Wo finde ich diese Konfigurationsdatei? Hab das System natürlich inzw. wieder mit 8.2 zum laufen gebracht. könnte aber ein Backup auf meinem 2. Raspi wiederherstellen und dann dir zukommen lassen. Würde allerdings etwas dauern.

**Comment by ospectreo** [comment]
Same problem with BatteryService
After adding this service to some sensor, all sensors going down

**Comment by jensweigele** [comment]
I'm able to reproduce the issue now.
I'm looking into it.
Did this really work with 0.8.2 and previous?

**Comment by jensweigele** [comment]
Problem ist mit dem aktuellen Master behoben.
Durch die "Community" Definitionen, wurde die UUID des Batterylevels ersetzt.
Alle Community Services und Characteristics haben von nun an das Prefix "Community: "

**Comment by kugelkopf123** [comment]
Moin Moin! Sorry ich bin immer noch nicht dazu gekommen, dir einen Log zu schicken aus meiner Testumgebung. Leider  ist es Zeitlich aktuell etwas knapp.  
Ist in der aktuellen Version via NPM also die 0.9.0 dieser Fehler behoben oder erst ab dem nächsten Major release? Also 2.0. ?

**Comment by sonntam** [comment]
Hatte genau dasselbe Problem wie @kugelkopf123. Mit dem Update auf den aktuellen master [6ddfddc](https://github.com/jensweigele/ioBroker.yahka/commit/6ddfddc8d1d68b3dc3d2a70f76b8dc46a0de56e1) klappt es nun. Jedoch musste ich in der HomeKit App auf dem iPhone die Bridge löschen und neu einbinden.
