### ISSUE TITLE
Crash Version 0.9.0 mit Redis

### ISSUE THREAD

**Issue by schmupu** [jensweigele/ioBroker.yahka#96]
eben die Version 0.9.0 installiert. Seitdem startet Yahka nicht mehr. Folgende Fehlermeldung tritt auf:

```

2019-01-25 23:22:30.909 - error: Caught by controller[0]: HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008A-0000-1000-8000-0026BB765291. Adding anyway.
2019-01-25 23:22:30.910 - error: Caught by controller[1]: HAP Warning: Characteristic 0000000F-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008A-0000-1000-8000-0026BB765291. Adding anyway.
2019-01-25 23:22:30.910 - error: Caught by controller[2]: HAP Warning: Characteristic 00000035-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008A-0000-1000-8000-0026BB765291. Adding anyway.
2019-01-25 23:22:30.910 - error: Caught by controller[3]: HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008A-0000-1000-8000-0026BB765291. Adding anyway.
2019-01-25 23:22:30.910 - error: Caught by controller[4]: HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008A-0000-1000-8000-0026BB765291. Adding anyway.
2019-01-25 23:22:30.910 - error: Caught by controller[5]: HAP Warning: Characteristic 0000000F-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008A-0000-1000-8000-0026BB765291. Adding anyway.
2019-01-25 23:22:30.910 - error: Caught by controller[6]: TypeError: Cannot read property 'val' of null
2019-01-25 23:22:30.910 - error: Caught by controller[6]: at convertStateValueToNumber (/opt/iobroker/node_modules/iobroker.yahka/main.js:2331:41)
2019-01-25 23:22:30.910 - error: Caught by controller[6]: at /opt/iobroker/node_modules/iobroker.yahka/main.js:2282:21
2019-01-25 23:22:30.910 - error: Caught by controller[6]: at Command.callback (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:238:17)
2019-01-25 23:22:30.911 - error: Caught by controller[6]: at normal_reply (/opt/iobroker/node_modules/redis/index.js:726:21)
2019-01-25 23:22:30.911 - error: Caught by controller[6]: at RedisClient.return_reply (/opt/iobroker/node_modules/redis/index.js:824:9)
2019-01-25 23:22:30.911 - error: Caught by controller[6]: at JavascriptRedisParser.returnReply (/opt/iobroker/node_modules/redis/index.js:192:18)
2019-01-25 23:22:30.911 - error: Caught by controller[6]: at JavascriptRedisParser.execute (/opt/iobroker/node_modules/redis-parser/lib/parser.js:574:12)
2019-01-25 23:22:30.911 - error: Caught by controller[6]: at Socket. (/opt/iobroker/node_modules/redis/index.js:274:27)
2019-01-25 23:22:30.911 - error: Caught by controller[6]: at emitOne (events.js:116:13)
2019-01-25 23:22:30.911 - error: Caught by controller[6]: at Socket.emit (events.js:211:7)
2019-01-25 23:22:30.911 - error: host.iobroker instance system.adapter.yahka.0 terminated with code 0 (OK)
2019-01-25 23:22:30.911 - info: host.iobroker Restart adapter system.adapter.yahka.0 because enabled


```
VG
Stübi

**Comment by jensweigele** [comment]
Probier mal den aktuellen master ("Installieren über Github") und gib kurz Bescheid.
Ich hatte ein ähnliches Problem auf meinem Echtsystem.

**Comment by schmupu** [comment]
Ja, gerade installiert! Mit der 0.9.1 über Github läuft es wieder. Danke für die Hilfe. 
VG aus Hamburg
Stübi
